/*
 nehan3.js
 Copyright (C) 2011, 2012, Watanabe Masaki<lambda.watanabe[at]gmail.com>

 licenced under MIT licence.

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
*/

var Nehan3;Nehan3||(Nehan3={});
(function(){var j={layout:{minFontSize:10,defFontSize:18,tabLength:4,defLeadingRate:1.8,rubySizeRate:0.5,captionSizeRate:0.65,captionMarginRate:1,blockMarginRate:0.8,readerBorder:1,acceptableResizeRate:0.6,headerScales:[2.4,2,1.6,1.4,1,1],indent:{indentBefore:2,indentAfter:1},blockquote:{indentBefore:2,indentAfter:1,fontSizeRate:0.9,border:1},fieldset:{indentBefore:1,indentAfter:0,fontSizeRate:0.9,border:1},textset:{tpart:{fontSizeRate:0.9}},dl:{indentBefore:0,indentAfter:0,dt:{indentBefore:0,indentAfter:0,
fontSizeRate:0.9},dd:{indentBefore:1,indentAfter:0,fontSizeRate:0.9}},ul:{indentBefore:1,indentAfter:1,listMark:"\u30fb",li:{fontSizeRate:0.9}},ol:{indentBefore:1,indentAfter:1,listMark:"\u30fb",li:{fontSizeRate:0.9}},scenario:{shead:{size:100,fontSizeRate:0.9},sfoot:{size:80,fontSizeRate:0.7},sbody:{fontSizeRate:1,marginRate:0.2}}},color:{defCharImgColor:"000000",labelCharImgColor:"FFFFFF"},className:{img:"nehan-img",line:"nehan-line",page:"nehan-page",wrap:"nehan-wrap",charImg:"nehan-char-img",
charIcon:"nehan-char-icon",forkedPage:"nehan-forked-page",alignedPage:"nehan-aligned-page",inlineReader:"nehan-inline-reader",errorMsg:"nehan-error-msg",textLine:"nehan-text-line",rubyLine:"nehan-ruby-line",labelLine:"nehan-label-line",labelLineBody:"nehan-label-line-body",rubyText:"nehan-ruby-text",caption:"nehan-caption",blockElement:"nehan-block-element",tocLink:"nehan-toc-link"},rex:{word:/[\w!\.\?\/\_:#;]+/,nvAttr:/(?:\S+)=["']?(?:(?:.(?!["']?\s+(?:\S+)=|["']))+.)["']?/g},tags:{single:["img",
"br","end-page"],tcy:["pack","tcy"],greedy:["pre"],block:"img,table,iframe,textarea,ireader,ipage".split(","),fork:"blockquote,ul,ol,li,dl,dt,dd,fieldset,indent,textset,scenario".split(","),toc:["part","chapter","section","subsection"],content:"blockquote,indent,table,textarea,iframe,ipage,ireader,shead,sbody,sfoot,tpart,fieldset,ul,ol,li,dl,dt,dd".split(",")},types:{textToken:["char","tcy","word","rb"]},system:{lang:"ja-jp",nobr:false,lexingBufferLen:2E3,enableYakuMetricsCheck:true,lineBreakCheckLevel:2},
charImgRoot:"http://nehan.googlecode.com/hg/char-img"},A={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS"},searchString:function(d){for(var a=0;a<d.length;a++){var g=d[a].string,h=d[a].prop;this.versionSearchString=d[a].versionSearch||d[a].identity;if(g){if(g.indexOf(d[a].subString)!=-1)return d[a].identity}else if(h)return d[a].identity}},
searchVersion:function(d){var a=d.indexOf(this.versionSearchString);return a==-1?void 0:parseFloat(d.substring(a+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},
{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",
versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};A.init();var x={init:function(){var d=A.browser.toLowerCase(),a=A.OS.toLowerCase(),g=navigator.userAgent;this.isIE=d=="explorer";this.isWin=a=="windows";this.isMac=a=="mac";this.isIPhone=navigator.platform=="iPhone";
this.isIPad=navigator.platform=="iPad";this.isIPod=navigator.platform=="iPod";this.isMobileSafari=this.isIPhone||this.isIPad||this.isIPod;this.isAndroid=/android/.test(g)}};x.init();var p={clone:function(d){var a;if(typeof d=="object")if(d instanceof Array){a=[];for(var g=0,h=d.length;g<h;g++)a[g]=this.clone(d[g])}else for(prop in a={},d)a[prop]=this.clone(d[prop]);else a=d;return a},cutQuote:function(d){return d.replace(/\"/g,"").replace(/\'/g,"")},cutTagHeadSpace:function(d){return d.replace(/[\s]+</g,
"<")},cutHeadSpace:function(d){return d.replace(/^[\s]+/,"")},cutHeadCRLF:function(d){return d.replace(/^\n+/g,"")},cutTailCRLF:function(d){return d.replace(/\n+$/g,"")},cutEdgeCRLF:function(d){return this.cutTailCRLF(this.cutHeadCRLF(d))},escape:function(d){return d.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/'/g,"&#039;").replace(/"/g,"&quot;")},filenameConcat:function(d,a){d=d==""?"":d.slice(-1)=="/"?d:d+"/";a=a==""?"":a[0]=="/"?a.substring(1,a.length):a;return d+a}},
w={eq:function(d){return function(a){return d==a}},onkeypress:function(d){return function(a){d(x.isIE?event.keyCode:a.keyCode||a.which)}}},t={copy:function(d,a){for(prop in a)d[prop]=a[prop];return d},init:function(d,a,g){for(prop in a)d[prop]=typeof g[prop]=="undefined"?a[prop]:g[prop];return d}},m={iter:function(d,a){for(var g=0,h=d.length;g<h;g++)a(d[g])},iteri:function(d,a){for(var g=0,h=d.length;g<h;g++)a(g,d[g])},map:function(d,a){for(var g=[],h=0,f=d.length;h<f;h++)g.push(a(d[h]));return g},
fold:function(d,a,g){for(var h=0,f=d.length;h<f;h++)a=g(a,d[h]);return a},filter:function(d,a){for(var g=[],h=0,f=d.length;h<f;h++){var c=d[h];a(c)&&g.push(c)}return g},find:function(d,a){for(var g=0,h=d.length;g<h;g++){var f=d[g];if(a(f))return f}return null},exists:function(d,a){return this.find(d,a)!=null}},n={html:function(d){var a=[];for(prop in d){var g=d[prop]+"",g=p.escape(g);d[prop]!=""&&a.push(prop+"='"+g+"'")}return a==[]?"":a.join(" ")},css:function(d){var a=[];for(prop in d){var g=d[prop]+
"",g=p.escape(g);a.push(prop+":"+g+";")}return a.join("")}},l={isStartTagName:function(d){return d.charAt(0)!="/"},isTcyTagName:function(d){return m.exists(j.tags.tcy,w.eq(d))},isSingleTagName:function(d){return m.exists(j.tags.single,w.eq(d))},isBlockTagName:function(d){return m.exists(j.tags.block,w.eq(d))},isForkPageTagName:function(d){return m.exists(j.tags.fork,w.eq(d))},isContentTagName:function(d){return m.exists(j.tags.content,w.eq(d))},start:function(d,a){var g="<"+d;if(typeof a!="undefined"||
a==null)var h=n.html(a),g=h!=""?[g,h].join(" "):g;g+=this.isSingleTagName(d)?" />":">";return g},wrap:function(d,a,g){return[this.start(d,a),g,"</"+d+">"].join("")},end:function(d){return"</"+d+">"}},q={isCharCountableToken:function(d){return!this.isTextToken(d)?false:/\s/.test(d.data)?false:d.type=="char"&&d.img?false:true},isEndPageToken:function(d){return d.type=="tag"&&d.data.name=="end-page"},isTextToken:function(d){return m.exists(j.types.textToken,w.eq(d.type))},isBlockToken:function(d){return d.type!=
"tag"?false:l.isBlockTagName(d.data.name)},isForkPageToken:function(d){return d.type!="tag"?false:l.isForkPageTagName(d.data.name)}},J={isTcy:function(d){return d.length!=2?false:d=="!!"||d=="!?"||d=="??"?true:d.match(/\d\d/)!=null}},r={isHeadNg:function(d){return/[\uff09\)\u300d\u3011\u3015\uff3d\]\u3002\u300f\uff1e\u3009\u300b\u3001\uff0e\.,]/.test(d)},isTailNg:function(d){return/[\uff08\(\u300c\u3010\uff3b\u3014\u300e\uff1c\u3008\u300a]/.test(d)},isTailConnectiveChar:function(d){return/[\u3001\u3002\.\uff0e,\uff0c\u300d\u300f\uff09]/.test(d)},
isKakkoStartChar:function(d){return/[\u300c\u300e\u3010\uff3b\uff08\u300a\u3008\u226a\uff1c\[\(]/.test(d)},isKakkoEndChar:function(d){return/[\u300d\u300f\u3011\uff3d\uff09\u300b\u3009\u226b\uff1e\]\)]/.test(d)},isKutenTouten:function(d){return/[\u3001\u3002,.]/.test(d)},isZenkaku:function(d){return escape(d).charAt(1)=="u"},isHankaku:function(d){return!this.isZenkaku(d)},isSmallKana:function(d){var a=d.charCodeAt(0);return m.exists([12353,12355,12357,12359,12361,12387,12419,12421,12423,12430,12449,
12451,12453,12455,12457,12483,12515,12517,12519,12526,12533,12534],function(d){return d==a})},ofImgSrc:function(d,a){a=typeof a!="undefined"?a:j.color.defCharImgColor;return p.filenameConcat(j.charImgRoot,d+"/"+a+".png")}},Q={getLevel:function(d){for(var a=j.tags.toc,g=0,h=a.length;g<h;g++)if(a[g]==d)return g;return 0}},K={RG:[0,36,73,109,146,182,219,255],B:[0,85,170,255],namedColors:{black:{r:0,g:0,b:0},red:{r:256,g:0,b:0},green:{r:0,g:256,b:0},blue:{r:0,g:0,b:256},white:{r:256,g:256,b:256}},findNear:function(d,
a){if(d==0||d==255)return d;for(var g=256,h=0,f=0;f<a.length;f++){var c=Math.abs(d-a[f]);c<g&&(g=c,h=a[f])}return h},get:function(d){d=d.replace("#","").toLowerCase();if(d=="000000"||d=="000"||d=="black")return"000000";if(d=="ffffff"||d=="fff"||d=="white")return"FFFFFF";if(this.namedColors[d])var a=this.namedColors[d],g=a.r,h=a.g,a=a.b;else if(/[^0-9a-f]/.test(d))return"000000";else d.length==3?(g=parseInt([d[0],d[0]].join(""),16),h=parseInt([d[1],d[1]].join(""),16),a=parseInt([d[2],d[2]].join(""),
16)):d.length==6&&(g=parseInt(d.substring(0,2),16),h=parseInt(d.substring(2,4),16),a=parseInt(d.substring(4,6),16));g=this.findNear(g,this.RG);h=this.findNear(h,this.RG);a=this.findNear(a,this.B);d=function(h){return h.length<=1?"0"+h:h};g=d(g.toString(16));h=d(h.toString(16));a=d(a.toString(16));return(g+h+a).toUpperCase()}},L=function(){function d(b){this.text=this._preprocess(b);this.pos=0;this.rb=""}var a=function(b,c){var e=b.indexOf(">",c+1);return e<0?"":b.substring(c,e+1)},g=function(b){b=
b.split(/\s+/);b.shift();return m.map(b,function(b){return b.replace(/=.+/,"")})},h=function(b){var c={},b=b.match(j.rex.nvAttr);if(b==null)return c;m.iter(b,function(b){if(b.match(/([\w\-]+)=(.+)/)){var b=RegExp.$1.toLowerCase(),e=p.cutQuote(RegExp.$2);c[b]=e}});return c},f=function(b){var b=b.replace(/[\s]+=[\s]+/g,"="),c=g(b),e=h(b);m.iter(c,function(b){typeof e[b]=="undefined"&&(e[b]=true)});return e},c=function(b){var c=b.replace("<","").replace("/>","").replace(">",""),b=c.split(/[\s\t\u3000]+/)[0].toLowerCase(),
c=f(c);return{type:"tag",data:{name:b,attr:c}}},b=function(c,e,h){var a=c.indexOf("</"+e,h),h=c.indexOf("<"+e,h);return a<0?-1:h<0||a<h?a:b(c,e,a+1)},e=function(c,e,h){e=b(c,e,h);return c.substring(h,e)};d.prototype={_preprocess:function(b){for(var c="",e=0;e<j.layout.tabLength;e++)c+="&nbsp;";b=b.replace(/(\t)/,function(){return c}).replace(/<([\w\-]+)/g,function(b,c){return"<"+c.toLowerCase()}).replace(/<\/([\w\-]+)/g,function(b,c){return"</"+c.toLowerCase()}).replace(/([^\n])<img/g,"$1\n<img").replace(/([^\n])<table/g,
"$1\n<table").replace(/([^\n])<end-page/g,"$1\n<end-page").replace(/([^\n])<blockquote/g,"$1\n<blockquote").replace(/([^\n])<indent/g,"$1\n<indent").replace(/([^\n])<iframe/g,"$1\n<iframe").replace(/([^\n])<ipage/g,"$1\n<ipage").replace(/([^\n])<ireader/g,"$1\n<ireader");j.system.nobr&&(b=b.replace(/<br>/gi,"").replace(/<br \/>/gi,""));return b},_lookChar:function(b){b=this.pos+(b||0);if(b==this.text.length)return"\n";if(b>this.text.length)throw"BufferEnd";return this.text.charAt(b)},_mapChar:function(b,
c){var e=c.charCodeAt(0),h={type:"char",data:c,hscaleImg:1,half:r.isHankaku(c),pos:b},a=function(b,c){h.img=b;h.hscaleImg=c;return h},f=function(b){h.cnv=b;return h};if(r.isSmallKana(c))return h.skana=true,h;if(c==" ")return f("&nbsp;");switch(e){case 12300:return a("kakko1",0.5);case 65378:return a("kakko1",0.5);case 12301:return a("kakko2",0.5);case 65379:return a("kakko2",0.5);case 12302:return a("kakko3",0.5);case 12303:return a("kakko4",0.5);case 65288:return a("kakko5",0.5);case 40:return a("kakko5",
0.5);case 65371:return a("kakko5",0.5);case 123:return a("kakko5",0.5);case 65289:return a("kakko6",0.5);case 41:return a("kakko6",0.5);case 65373:return a("kakko6",0.5);case 125:return a("kakko6",0.5);case 65308:return a("kakko7",0.5);case 60:return a("kakko7",0.5);case 12296:return a("kakko7",0.5);case 65310:return a("kakko8",0.5);case 62:return a("kakko8",0.5);case 12297:return a("kakko8",0.5);case 12298:return a("kakko9",0.5);case 8810:return a("kakko9",0.5);case 12299:return a("kakko10",0.5);
case 8811:return a("kakko10",0.5);case 65339:return a("kakko11",0.5);case 12308:return a("kakko11",0.5);case 91:return a("kakko11",0.5);case 65341:return a("kakko12",0.5);case 12309:return a("kakko12",0.5);case 93:return a("kakko12",0.5);case 12304:return a("kakko17",0.5);case 12305:return a("kakko18",0.5);case 65306:return a("tenten",0.5);case 58:return a("tenten",0.5);case 12290:return a("kuten",0.5);case 65377:return a("kuten",0.5);case 65294:return a("period",1);case 46:return a("period",1);case 12289:return a("touten",
0.5);case 65380:return a("touten",0.5);case 44:return a("touten",0.5);case 65292:return a("touten",0.5);case 65374:return a("kara",1);case 12316:return a("kara",1);case 8230:return a("mmm",1);case 8229:return a("mm",1);case 12317:return a("dmn1",1);case 12319:return a("dmn2",1);case 65309:return a("equal",1);case 61:return a("equal",1);case 12540:return f("\uff5c");case 45:return f("\uff5c");case 8213:return f("\uff5c");case 65293:return f("\uff5c");case 9472:return f("\uff5c");case 8593:return f("&#8594;");
case 8594:return f("&#8595;");case 8658:return f("&#8595;");case 8595:return f("&#8592;");case 8592:return f("&#8593;")}return h},_mapTag:function(b,c){var e=c.data.name;return e=="ruby"?this._readRubyTag(b,c):e=="img"?this._readImgTag(b,c):l.isTcyTagName(e)?this._readTcyTag(b,c):l.isContentTagName(e)?this._readContentTag(b,c):c},_skipComment:function(b){this.pos=this.text.indexOf("--\>",b)+3},_readTag:function(b){var e=a(this.text,b),h=c(e);h.pos=b;this.pos+=e.length;return h},_readContentTag:function(b,
c){var a=e(this.text,c.data.name,this.pos);c.data.content=a;this.pos+=a.length+c.data.name.length+3;return c},_readTagGroup:function(b,h){var f=j.tags.group[h.data.name],d=e(this.text,h.data.name,this.pos);this.pos+=d.length+h.data.name.length+3;h.data.childs={};m.iter(f.childs,function(b){var f;f=d.indexOf("<"+b);if(f<0)f=null;else{var k=a(d,f);if(k=="")f=null;else{var g=c(k);g.data.content=e(d,b,f+k.length);f=g.data}}f!=null&&(h.data.childs[b]=f)});return h},_readRubyTag:function(b,c){var a={type:"ruby",
pos:b},h=e(this.text,c.data.name,this.pos);this.pos+=h.length+7;if(h.match(/<rt>([^<]+)<\/rt>/i))a.yomi=RegExp.$1;if(h.match(/<rb>([^<]+)<\/rb>/i))this.rb=a.kanji=RegExp.$1;else if(h.match(/([^<]+)<rt>/i))this.rb=a.kanji=RegExp.$1;return a},_readTcyTag:function(b,c){var a=e(this.text,c.data.name,this.pos);this.pos+=a.length+c.data.name.length+3;return{type:"tcy",data:a,pos:b}},_readImgTag:function(b,c){return c},_readRbChar:function(b){var c=this.rb.charAt(0);this.rb=this.rb.substring(1);b=this._mapChar(b,
c);b.type="rb";return b},_readSpecialChar:function(b,c){var e=this.text.substring(b).match(/&[a-zA-Z#0-9]+;/),e=e?e.toString():c;return e==""||e.length==1||e.length>10?(e=this._mapChar(b,c),this.pos++,e):(this.pos+=e.length,{type:"char",data:e,hscaleImg:1,half:true,pos:b})},_readChar:function(b,c){var e=this._mapChar(b,c);this.pos++;return e},_readWord:function(b,c){var e=this.text.substring(b).match(j.rex.word),e=e?e.toString():c,a=J.isTcy(e)?"tcy":"word";this.pos+=e.length;return e.length==1?this._mapChar(b,
e):{type:a,data:e,pos:b}},getPos:function(){return this.pos},getToken:function(){var b=this.pos;if(this.rb!="")return this._readRbChar(b);else var c=this._lookChar();if(c=="<"){try{if(this._lookChar(1)=="!")return this._skipComment(b),this.getToken()}catch(e){}c=this._readTag(b);return this._mapTag(b,c)}else return c=="&"?this._readSpecialChar(b,c):c.match(j.rex.word)?this._readWord(b,c):this._readChar(b,c)}};return d}(),y=function(){function d(a){this.lexer=new L(a);this.tokens=[];this.pos=0;this.eof=
false;this.bufferSize=j.system.lexingBufferLen;this._doBuffer()}d.prototype={_doBuffer:function(){try{for(var a=0;a<this.bufferSize;a++)this.tokens.push(this.lexer.getToken())}catch(d){this.eof=true}},setPos:function(a){this.pos=a},getPos:function(){return this.pos},isEnd:function(){return this.eof&&this.pos>=this.tokens.length-1},stepPos:function(a){this.pos+=typeof a!="undefined"?a:1},lookToken:function(a){return this.lookTokenByIndex(this.pos+(a||0))},lookTokenByIndex:function(a){if(this.eof&&
a>=this.tokens.length)throw"BufferEnd";a>=this.tokens.length&&this._doBuffer();var d=this.tokens[a];d.index=a;return d},findUntil:function(a,d,h){for(;;){if(a<0)break;else if(a>=this.tokens.length)break;else{var f=this.lookTokenByIndex(a);if(h(f))return f}a+=d}return null},getToken:function(){var a=this.lookToken();this.pos++;return a},getBufferRestSize:function(){return Math.max(this.tokens.length-this.pos-1,0)},skipUntil:function(a){for(;;){var d=this.lookToken();if(!a(d))break;this.stepPos(1)}},
skipUntilCRLF:function(){this.skipUntil(function(a){return!q.isTextToken(a)?false:a.data=="\r"||a.data=="\n"})},skipCRLF:function(){var a=this.lookToken();q.isTextToken(a)&&(a.data=="\r"?(this.stepPos(1),this.skipCRLF()):a.data=="\n"&&this.stepPos(1))}};return d}(),B=function(){function d(a){this.tags=[];this.tocs=[];this.topicPath=[];this.lastTopicPath=null;this.textSpaceAfter=this.textSpaceBefore=this.seekTextPos=this.seekCharCount=this.seekPageNo=this.seekNextLine=this.seekNextChar=0;this.lineChars=
[];this.rubyList=[];this.inlinePages=[];this.curToc=null;this.greedyMode=false;this.labelAttr=null;this.fontColor=j.color.defCharImgColor;this.updateFontSize(a.fontSize)}d.prototype={snap:function(){var a={},d=p.clone,h="tags,tocs,topicPath,lastTopicPath,seekNextChar,seekNextLine,seekCharCount,seekTextPos,textSpaceBefore,textSpaceAfter,lineChars,rubyList,inlinePages,curToc,greedyMode,labelAttr,fontSize,fontSize2,fontSize4,fontColor".split(",");for(prop in h)a[prop]=d(this[prop]);return a},restoreSnap:function(a){for(prop in a)this[prop]=
a[prop]},createBlock:function(a,d){return t.init({},{type:"block",name:"",width:0,height:0,content:""},d)},createImage:function(a,d){return t.init(this.createBlock(a,d),{src:""},d)},createInlineFrame:function(a,d){return t.init(this.createBlock(a,d),{src:"",frameborder:0},d)},createCaption:function(a,d){return t.init({},{type:"caption",data:"",captionPos:"",fontSize:a.captFontSize,height:a.captFontSize+a.captMargin,"text-align":"center","margin-top":0,"margin-bottom":0},d)},createRuby:function(a,
d){return t.init({},{type:"ruby",data:"",fontSize:this.fontSize2,textFontSize:this.fontSize,direction:a.direction,position:{x:0,y:0}},d)},createLine:function(a){if(this.labelAttr!=null){var d=this.createLabelLine(a,this.labelAttr);this.textSpaceBefore=Math.max(0,this.textSpaceBefore-a.labelSpace*2);this.textSpaceAfter=Math.max(0,this.textSpaceAfter-a.labelSpace*2);this.labelAttr=null}else d=this.createTextLine(a),this.fixRubyPos(a);this.lineChars=[];this.rubyList=[];this.seekNextChar=0;return d},
createTextLine:function(a){var d=this.getMaxFontSizeOfLine(a),h=a.enableRuby?Math.floor(d*a.leadingRate):d,f=this.getTextSpaceSize(),c=a.isVertical?h:a.maxNextChar-f,h=a.isVertical?a.maxNextChar-f:h,d={width:a.isVertical?d:a.width,height:a.isVertical?a.height:d};return{type:"line",width:c,height:h,direction:a.direction,fontSize:a.fontSize,textLineSize:d,rubyLineSize:{width:a.enableRuby?a.isVertical?c-d.width:a.width:0,height:a.enableRuby?a.isVertical?a.height:h-d.height:0},childs:this.lineChars,rubyList:this.rubyList}},
createLabelLine:function(a,d){var h=this.getMaxFontSizeOfLine(a),f=Math.floor(h*a.leadingRate),h=a.isVertical?f:this.seekNextChar+2*a.labelSpace,f=a.isVertical?this.seekNextChar+2*a.labelSpace:f;return{type:"label-line",width:h,height:f,direction:a.direction,fontSize:a.fontSize,textLineSize:{width:h,height:f},rubyLineSize:{width:0,height:0},childs:this.lineChars,textSpaceBefore:a.labelSpace,textSpaceAfter:a.labelSpace,rubyList:[],attr:d}},createPage:function(a,d,h,f){return{type:"page",direction:a,
width:d,height:h,childs:f}},createErrorMsg:function(a,d){var h=a.fontSize*5;return this.createInlineReader(a,{direction:"horizontal",width:a.isVertical?h:a.maxNextChar,height:a.isVertical?a.maxNextChar:h,theme:"error","class":"error",nopager:true,content:d})},createInlineReader:function(a,d){return t.init({},{type:"ireader","class":"",direction:a.direction,width:0,height:0,border:j.layout.readerBorder,fontSize:a.fontSize,theme:"",syntax:"",nopager:false,content:""},d)},getTocs:function(){return this.tocs},
pushTextToken:function(a){a.type=="char"||a.type=="rb"||a.type=="tcy"?this.pushCharToken(a):a.type=="word"&&this.pushWordToken(a)},pushTagToken:function(a){this.lineChars.push(a)},pushCharToken:function(a){this.seekNextChar+=a.stepSize;this.lineChars.push(a);q.isCharCountableToken(a)&&this.seekCharCount++;this.curToc!=null&&(this.curToc.title+=a.data)},pushWordToken:function(a){this.seekNextChar+=a.stepSize;this.lineChars.push(a);this.seekCharCount+=a.data.length;this.curToc!=null&&(this.curToc.title+=
a.data)},pushTopicPath:function(a){this.lastTopicPath!=null&&(a.level<this.lastTopicPath.level?(this.topicPath.pop(),this.topicPath.pop()):a.level==this.lastTopicPath.level&&this.topicPath.pop());this.topicPath.push(a);this.lastTopicPath=a},pushTocStartToken:function(a){var d=a.data.attr;this.curToc={level:d.level,title:"",pageNo:this.seekPageNo,id:d.id};this.tocs.push(this.curToc);this.pushTagToken(a)},pushTocEndToken:function(a){this.pushTopicPath(this.curToc);this.curToc=null;this.pushTagToken(a)},
pushRubyToken:function(a,d){this.rubyList.push(this.createRuby(a,{fontSize:Math.floor(this.fontSize*j.layout.rubySizeRate),textFontSize:this.fontSize,data:d.yomi,position:a.isVertical?{x:0,y:this.seekNextChar}:{x:this.seekNextChar,y:Math.floor((a.lineSpaceRate-j.layout.rubySizeRate)*this.fontSize/2)}}))},fixRubyPos:function(a){var d=this.getMaxFontSizeOfLine(a);d!=a.fontSize&&m.iter(this.rubyList,function(h){if(h.textFontSize<d)a.isVertical?h.position.x=-Math.floor((d-h.textFontSize)/2):h.position.y=
Math.floor((d-h.textFontSize)*(1+a.lineSpaceRate))})},startLabel:function(a,d){this.textSpaceBefore+=a.labelSpace*2;this.textSpaceAfter+=a.labelSpace*2;this.labelAttr=d.data.attr},endLabel:function(){},getTextSpaceSize:function(){return this.textSpaceBefore+this.textSpaceAfter},getRestCharSpace:function(a){return a.maxNextChar-this.seekNextChar-this.getTextSpaceSize()},getRestLineSpace:function(a){return a.maxNextLine-this.seekNextLine},getRestWidth:function(a){return a.isVertical?this.getRestLineSpace(a):
this.getRestCharSpace(a)},getRestHeight:function(a){return a.isVertical?this.getRestCharSpace(a):this.getRestLineSpace(a)},getMaxFontSizeOfLine:function(){return m.fold(this.lineChars,j.layout.minFontSize,function(a,d){return typeof d.fontSize!="undefined"&&d.fontSize>a?d.fontSize:a})},getCurFontSize:function(a){for(i=this.tags.length-1;i>=0;i--){var d=this.tags[i];if(d.name=="font"&&typeof d.attr.scale!="undefined")return Math.floor(a*d.attr.scale)}return a},getCurFontColor:function(){for(i=this.tags.length-
1;i>=0;i--){var a=this.tags[i];if(a.name=="font"&&typeof a.attr.color!="undefined")return a.attr.color}return j.color.defCharImgColor},updateFontSize:function(a){this.fontSize=a;this.fontSize2=Math.floor(a/2);this.fontSize4=Math.floor(a/4)},updateFontColor:function(a){this.fontColor=K.get(a)},pushTag:function(a){this.tags.push(a)},popTag:function(a){for(var d=[];this.tags.length>0;){var h=this.tags.pop();if(h.name==a)break;d.push(h)}for(;d.length>0;)this.tags.push(d.pop())}};return d}(),F={code:{fontSizeRate:0.7,
leadingRate:1.8},error:{fontSizeRate:1,leadingRate:1.8}},u=function(){function d(a){t.init(this,{direction:"vertical",theme:null,leadingRate:j.layout.defLeadingRate,width:400,height:300,fontSize:16,enableRuby:true,disableTailSpace:false,charImgColor:"000000"},a);this.update()}var a={vertical:{"page-size":"width","block-float":"right","line-text-align":"center","ruby-line-text-align":"left","margin-before":"margin-top","margin-after":"margin-bottom","margin-prev":"margin-right","margin-next":"margin-left",
"border-before":"border-top","border-after":"border-bottom","border-prev":"border-right","border-next":"border-left",dummy:""},horizontal:{"page-size":"height","block-float":"left","line-text-align":"left","ruby-line-text-align":"left","margin-before":"margin-left","margin-after":"margin-right","margin-prev":"margin-top","margin-next":"margin-bottom","border-before":"border-left","border-after":"border-right","border-prev":"border-top","border-next":"border-bottom",dummy:""}},g={vertical:{"max-next-line":"width"},
horizontal:{"max-next-line":"height"}};d.prototype={update:function(){if(this.theme!=null)this.fontSize=Math.floor(this.fontSize*(this.theme.fontSizeRate||1)),this.leadingRate=this.theme.leadingRate||this.leadingRate;this.isVertical=this.direction.match(/vertical/)?true:false;this.lineSpaceRate=this.leadingRate-1;this.blockMargin=Math.floor(this.fontSize*j.layout.blockMarginRate);this.labelSpace=Math.floor(this.fontSize*this.lineSpaceRate/2);this.captFontSize=Math.floor(this.fontSize*j.layout.captionSizeRate);
this.captMargin=Math.floor(this.captFontSize*j.layout.captionMarginRate);this.isVertical?(this.spaceForHeadNG=this.disableTailSpace?0:Math.floor(this.fontSize/2),this.maxNextChar=this.height-this.spaceForHeadNG,this.maxBlockWidth=this.maxNextLine=this.width,this.maxBlockHeight=this.maxNextChar-this.blockMargin):(this.spaceForHeadNG=this.disableTailSpace?0:this.fontSize,this.maxNextChar=this.width-this.spaceForHeadNG,this.maxNextLine=this.height,this.maxBlockWidth=this.maxNextChar-this.blockMargin,
this.maxBlockHeight=this.height)},getCssProp:function(h){return a[this.direction][h]},getProp:function(a){return g[this.direction][a]},getBlockRestWidth:function(a){return this.isVertical?a:this.maxBlockWidth-a},getBlockRestHeight:function(a){return this.isVertical?this.maxBlockHeight-a:a}};return d}(),G=function(){function d(a){this.forks=[];this.rest_size_list=a}function a(a,f,c){this.lexer=a;this.layout=f;this.ctx=typeof c!="undefined"?c:new B(f);this.forkset=null;this.pushBlocks=[];this.finish=
false;this.onParseElementBefore=function(b,c,a,h){return h}}var g=function(a,f){var c=a.isVertical?f.width||0:f.height||0;if(f.type=="page"&&f.tail)c=f.size;typeof f.border!="undefined"&&(c+=f.border*2);return c};d.prototype={add:function(a){this.forks.push(a)},hasNext:function(){return m.exists(this.forks,function(a){return a.hasNext()})},mergePages:function(a,f,c){if(c.length==1)return c[0];var b=m.fold(c,0,function(b,c){var e=g(a,c);return e>b?e:b}),e=a.getProp("max-next-line");m.iter(c,function(c){c[e]=
c.size=b});return f.createPage(a.direction,a.isVertical?b:a.width,a.isVertical?a.height:b,c)},yieldPage:function(a,f){var c=a.getProp("max-next-line"),b=this.rest_size_list.length>0?this.rest_size_list.shift():a[c],e=m.map(this.forks,function(e){var a=e.layout[c];e.args=e.args||{};e.layout[c]=b;e.args.border&&(e.layout[c]-=e.args.border*2);a!=e.layout[c]&&e.layout.update();e=e.parsePage(e.args);e.forked=true;return e});return this.mergePages(a,f,e)}};a.prototype={getContext:function(){return this.ctx},
hasNext:function(){return!this.finish},hasForkNext:function(){return m.exists(this.forks,function(a){return a.hasNext()})},findTextToken:function(a,f,c,b){for(var e=null,d={token:null,tags:[]},s=b;s<b+50;s++){var o=a.lookTokenByIndex(s);if(q.isBlockToken(o))break;if(q.isTextToken(o)){this.parseMetrics(a,f,e==null?c:e,o);d.token=o;break}if(o.type=="tag"){d.tags.push(o);var g=o.data.name;if(g=="font")e=e==null?p.clone(c):e,e.pushTag(o.data),e.fontSize=e.getCurFontSize(f.fontSize);else if(g=="/font")e=
e==null?p.clone(c):e,e.popTag("font"),e.fontSize=e.getCurFontSize(f.fontSize)}}return d},pushTextToLine:function(a,f,c,b){var e=c.getRestCharSpace(f),d=this.findTextToken(a,f,c,b.index+1);if(!(c.seekNextChar==0&&b.data==" "&&d.token.type=="word"))if(d.token==null||d.token.data=="\r"||d.token.data=="\n")c.pushTextToken(b);else if(e-b.stepSize>=d.token.stepSize)c.pushTextToken(b);else{if(j.system.lineBreakCheckLevel==0)throw"LineEnd";if(r.isTailNg(b.data))throw a.setPos(b.index),"LineEnd";if(!r.isHeadNg(d.token.data)||
d.token.type=="word")throw c.pushTextToken(b),a.skipCRLF(),"LineEnd";if(j.system.lineBreakCheckLevel==1)throw"LineEnd";e=this.findTextToken(a,f,c,d.token.index+1);if(e.token==null||!r.isHeadNg(e.token.data)){e.token.fontSize=f.fontSize;c.pushTextToken(b);c.pushTextToken(d.token);a.setPos(d.token.index+1);a.skipCRLF();for(b=0;b<d.tags.length;b++)this.parseLineTag(a,f,c,d.tags[b]);throw"LineEnd";}a.setPos(b.index);throw"LineEnd";}},pushLongWordToLine:function(a,f,c,b){var e=c.getRestCharSpace(f),d=
Math.floor(e/c.fontSize2),s=b.data.length,e=b.data.substring(0,d),d=b.data.substring(d,s),s=p.clone(b);s.data=e;this.parseMetrics(a,f,c,s);c.pushTextToken(s);a.setPos(b.index);b.data=d;this.parseMetrics(a,f,c,b);throw"LineEnd";},pushElementToPage:function(a,f,c,b,e){a=g(f,e);if(c.seekNextLine+a>f.maxNextLine)throw"Overflow";c.seekNextLine+=a;b.size+=a;b.childs.push(e);if(c.seekNextLine==f.maxNextLine)throw"EndPage";},parseMetrics:function(a,f,c,b){b.type=="char"||b.type=="rb"?b.src?this.parseMetricsIconChar(a,
f,c,b):f.isVertical&&b.img?this.parseMetricsImgChar(a,f,c,b):this.parseMetricsChar(a,f,c,b):b.type=="tcy"?this.parseMetricsTcy(a,f,c,b):b.type=="word"&&this.parseMetricsWord(a,f,c,b)},parseMetricsChar:function(a,f,c,b){b.fontSize=c.fontSize;b.stepSize=c.fontSize;if(f.isVertical)if(b.cnv&&b.cnv=="&nbsp;")b.stepSize=c.fontSize2;else{if(b.hscaleImg!=1)b.stepSize=Math.floor(c.fontSize*b.hscaleImg)}else if(b.half)b.stepSize=c.fontSize2},parseMetricsImgChar:function(a,f,c,b){this.parseMetricsChar(a,f,c,
b);if(f.isVertical)b.color=c.fontColor;if(j.system.enableYakuMetricsCheck&&!(b.img.indexOf("kakko")<0&&b.img!="touten"&&b.img!="kuten")){var e=function(b){return q.isTextToken(b)||b.type=="ruby"},d=a.findUntil(b.index-1,-1,e),f="";if(d!=null)q.isTextToken(d)?f=d.data:d.type=="ruby"&&(f=d.kanji.substring(-1));a=a.findUntil(b.index+1,1,e);e="";if(a!=null)q.isTextToken(a)?e=a.data:a.type=="ruby"&&(e=a.kanji.substring(0,1));if(r.isKakkoStartChar(b.data)&&f!=""){if(!r.isKakkoStartChar(f)&&!r.isKutenTouten(f))b["margin-before"]=
c.fontSize2,b.stepSize=c.fontSize}else if(r.isKakkoEndChar(b.data)&&e!=""){if(!r.isKakkoEndChar(e)&&!r.isKutenTouten(e))b["margin-after"]=c.fontSize2,b.stepSize=c.fontSize}else if(b.img=="touten"&&e!=""){if(!r.isKakkoEndChar(e))b["margin-after"]=c.fontSize2,b.stepSize=c.fontSize}else if(b.img=="kuten"&&e!=""&&!r.isKakkoEndChar(e))b["margin-after"]=c.fontSize2,b.stepSize=c.fontSize}},parseMetricsIconChar:function(a,f,c,b){a=f.isVertical?b.height:b.width;b.fontSize=a;b.stepSize=a},parseMetricsTcy:function(a,
f,c,b){b.fontSize=c.fontSize;b.stepSize=c.fontSize},parseMetricsWord:function(a,f,c,b){b.fontSize=c.fontSize;b.stepSize=b.data.length*c.fontSize2},parseChar:function(a,f,c,b){if(b.data!="\r"){if(b.data=="\n")throw"LineEnd";b.data==" "&&!c.greedyMode&&a.skipUntil(function(b){return b.type=="char"&&b.data==" "});this.parseMetrics(a,f,c,b);this.pushTextToLine(a,f,c,b)}},parseWord:function(a,f,c,b){typeof b.stepSize=="undefined"&&this.parseMetrics(a,f,c,b);b.stepSize>f.maxNextChar?this.pushLongWordToLine(a,
f,c,b):this.pushTextToLine(a,f,c,b)},parseRuby:function(a,f,c,b){c.pushRubyToken(f,b)},parseFontStart:function(a,f,c,b){a=b.data.attr;if(typeof a.scale!="undefined")f=a.scale=parseFloat(a.scale),c.updateFontSize(Math.floor(c.fontSize*f));typeof a.color!="undefined"&&c.updateFontColor(a.color);c.pushTag(b.data);c.pushTagToken(b)},parseFontEnd:function(a,f,c,b){c.pushTagToken(b);c.popTag("font");a=c.getCurFontSize(f.fontSize);f=c.getCurFontColor();c.updateFontSize(a);c.updateFontColor(f)},parseHeaderStart:function(a,
f,c,b){var e=parseInt(b.data.name.substring(1))-1;b.data.name="font";b.data.attr.family="Meiryo";b.data.attr.scale=j.layout.headerScales[e];this.parseFontStart(a,f,c,b)},parseHeaderEnd:function(a,f,c,b){b.data.name="/font";this.parseFontEnd(a,f,c,b);a.skipCRLF();throw"LineEnd";},parseTocStart:function(a,f,c,b){a=b.data.attr;a.level=parseInt(a.level||0);a.id=a.id||"";c.pushTocStartToken(b)},parseTocEnd:function(a,f,c,b){c.pushTocEndToken(b)},parseLabelStart:function(a,f,c,b){a.skipCRLF();c.updateFontColor(j.color.labelCharImgColor);
c.startLabel(f,b)},parseLabelEnd:function(a,f,c,b){a=c.getCurFontColor();c.updateFontColor(a);c.endLabel(f,b);throw"LineEnd";},parseIcon:function(a,f,c,b){var e=b.data.attr;b.width=parseInt(e.width||c.fontSize);b.height=parseInt(e.height||c.fontSize);b.src=e.src;b.type="char";delete b.data;b.data="";this.parseMetrics(a,f,c,b);this.pushTextToLine(a,f,c,b)},parseLineTag:function(a,f,c,b){switch(b.data.name){case "br":throw"LineEnd";case "pre":c.greedyMode=true;break;case "/pre":c.greedyMode=false;break;
case "font":this.parseFontStart(a,f,c,b);break;case "/font":this.parseFontEnd(a,f,c,b);break;case "h1":case "h2":case "h3":case "h4":case "h5":case "h6":this.parseHeaderStart(a,f,c,b);break;case "/h1":case "/h2":case "/h3":case "/h4":case "/h5":case "/h6":this.parseHeaderEnd(a,f,c,b);break;case "toc":this.parseTocStart(a,f,c,b);break;case "/toc":this.parseTocEnd(a,f,c,b);break;case "part":case "chapter":case "section":case "subsection":b.data.attr.level=Q.getLevel(b.data.name);b.data.name="toc";this.parseTocStart(a,
f,c,b);break;case "/part":case "/chapter":case "/section":case "/subsection":b.data.name="/toc";this.parseTocEnd(a,f,c,b);break;case "label":this.parseLabelStart(a,f,c,b);break;case "/label":this.parseLabelEnd(a,f,c,b);break;case "icon":this.parseIcon(a,f,c,b);break;default:c.pushTagToken(b)}},parseLine:function(a,f,c){try{for(;;){var b=a.getToken();switch(b.type){case "char":case "rb":case "tcy":this.parseChar(a,f,c,b);break;case "word":this.parseWord(a,f,c,b);break;case "ruby":this.parseRuby(a,
f,c,b);break;case "tag":this.parseLineTag(a,f,c,b)}}}catch(e){return c.createLine(f)}},parseBlockCaptions:function(a,f,c,b){var e=[];m.iter(["caption-head","caption-foot"],function(c){b[c]&&e.push(f.createCaption(a,{data:b[c],captionPos:c,"margin-bottom":c=="caption-head"?a.captMargin:0,"margin-top":c=="caption-foot"?a.captMargin:0}))});return e},parseBlockSizeAttr:function(a,f,c){a={width:0,height:0,border:0,"font-size":a.fontSize};for(prop in a)c[prop]=parseInt(typeof c[prop]=="undefined"?a[prop]:
c[prop]);return c},parseBlockSize:function(a,f,c,b){var e=c.border*2,d=f.getRestWidth(a),s=f.getRestHeight(a),b=m.fold(b,0,function(a,b){return a+b.height});if(c.width<=0||c.height<=0)return c.error="block size invalid("+c.width+","+c.height+")",c;var f=(a.isVertical?c.width:c.width+a.blockMargin)+e,g=(a.isVertical?c.height+a.blockMargin:c.height)+e+b;if(f<d&&g<s)return c;if(f<a.maxBlockWidth&&g<a.maxBlockHeight)throw"Overflow";f>d&&(g=d*g/f,f=Math.max(1,Math.floor(d)),g=Math.max(1,Math.floor(g)));
g>s&&(f=Math.floor(f*s/g),g=Math.floor(s));d=j.layout.acceptableResizeRate*c.width;s=j.layout.acceptableResizeRate*c.height;c.width=Math.max(0,(a.isVertical?f:f-a.blockMargin)-e);c.height=Math.max(0,(a.isVertical?g-a.blockMargin:g)-e-b);if(c.width<d||c.height<s)c.error="try to resize block, but not acceptable for this layout("+c.width+","+c.height+")";return c},parseImg:function(a,f,c,b){var b=this.parseBlockSizeAttr(f,c,b.data.attr),e=c.createImage(f,{name:"img",width:b.width,height:b.height,border:b.border,
src:b.src});return this.parseBlockElement(a,f,c,e,b)},parseTable:function(a,f,c,b){var e=this.parseBlockSizeAttr(f,c,b.data.attr),b=c.createBlock(f,{width:e.width,height:e.height,content:b.data.content,name:b.data.name});return this.parseBlockElement(a,f,c,b,e)},parseTextarea:function(a,f,c,b){var e=this.parseBlockSizeAttr(f,c,b.data.attr),b=c.createBlock(f,{width:e.width,height:e.height,content:b.data.content,name:b.data.name}),b=this.parseBlockElement(a,f,c,b,e);return t.copy(b,{onclick:e.onclick||
""})},parseInlineFrame:function(a,f,c,b){var e=this.parseBlockSizeAttr(f,c,b.data.attr),b=c.createInlineFrame(f,{width:e.width,height:e.height,content:b.data.content,name:b.data.name,src:e.src||"",frameborder:parseInt(e.frameborder||0)});return this.parseBlockElement(a,f,c,b,e)},parseInlinePage:function(a,f,c,b){t.copy(b.data.attr,{nopager:true});return this.parseInlineReader(a,f,c,b)},parseInlineReader:function(a,f,c,b){var e=b.data.attr;e.border=typeof e.border!="undefined"?parseInt(e.border):j.layout.readerBorder;
e=this.parseBlockSizeAttr(f,c,e);b=c.createInlineReader(f,{"class":e["class"]||"",direction:e.direction||f.direction,width:e.width,height:e.height,border:e.border,fontSize:parseInt(e["font-size"]||f.fontSize),theme:e.theme||"",syntax:e.syntax||"",nopager:e.nopager,content:p.cutHeadCRLF(b.data.content)});return this.parseBlockElement(a,f,c,b,e)},parseBlockElement:function(a,f,c,b,e){t.init(b,{"class":e["class"]||"",border:e.border,align:"",direction:f.direction},e);var d=this.parseBlockCaptions(f,
c,b,e),b=this.parseBlockSize(f,c,b,d);if(b.error)return c.createErrorMsg(f,"&lt;"+b.name+"&gt; "+b.error);d.length>0&&(b=this.parseBlockWithCaption(a,f,c,b,d));if(e.pushed)return this.parseBlockWithPush(a,f,c,b);else b.align!=""&&(b=this.parseBlockWithAlign(a,f,c,b));return b},parseBlockWithCaption:function(a,d,c,b,e){var k=[b],a=b.width,g=b.height;m.iter(e,function(a){g+=a.height;a.captionPos=="caption-head"?k.unshift(a):k.push(a)});c=c.createPage(b.direction,a,g,k);t.copy(c,{"class":b["class"]||
"",direction:b.direction,align:b.align});delete b.align;delete b["class"];return c},parseBlockWithPush:function(a,d,c,b){var e=d.blockMargin,k=d.isVertical?b.width+e:b.height+e;if(c.seekNextLine+k<d.maxNextLine)c.seekNextLine+=k,b["margin-prev"]=e,b.push_size=k,this.pushBlocks.push(b);return this.parseElement(a,d,c)},parseBlockWithAlign:function(d,f,c,b){var e=b.align=="top"||b.align=="left",k=b.direction==f.direction,g=f.getBlockRestWidth(b.width),o=f.getBlockRestHeight(b.height),j=c.seekNextLine;
c.seekNextLine=0;d=new a(d,new u({width:g,height:o,fontSize:f.fontSize,direction:f.direction,disableTailSpace:k}),c);d.aligned=true;d.parent=this;d.offset=j;k={};k[e?"margin-before":"margin-after"]=f.blockMargin;k=d.parsePage(k);c.seekNextLine=j;k.aligned=true;this.forkset=d.forkset;return c.createPage(f.direction,f.isVertical?b.width:f.width,f.isVertical?f.height:b.height,e?[b,k]:[k,b])},parseBlockTag:function(a,d,c,b){a.stepPos();a.skipCRLF();switch(b.data.name){case "img":return this.parseImg(a,
d,c,b);case "table":return this.parseTable(a,d,c,b);case "textarea":return this.parseTextarea(a,d,c,b);case "iframe":return this.parseInlineFrame(a,d,c,b);case "ipage":return this.parseInlinePage(a,d,c,b);case "ireader":return this.parseInlineReader(a,d,c,b)}return null},parseIndent:function(a,d,c,b){var e=b.data.attr,k=j.layout.indent;e.before=parseInt(e.before||k.indentBefore);e.after=parseInt(e.after||k.indentAfter);if(e.count)e.count=e.before=e.after=parseInt(e.count);e.border=parseInt(e.border||
0);e["margin-before"]=d.fontSize*e.before;e["margin-after"]=d.fontSize*e.after;return this.parseSingleForkPage(a,d,c,b)},parseBlockquote:function(a,d,c,b){var e=b.data.attr,k=j.layout.blockquote;e["font-size"]=parseInt(e["font-size"]||Math.floor(d.fontSize*k.fontSizeRate));e.border=typeof e.border!="undefined"?parseInt(e.border):k.border;b.data.content=l.wrap("indent",{before:k.indentBefore,after:k.indentAfter,theme:e.theme||"",syntax:e.syntax||""},b.data.content);e.theme="";e.syntax="";return this.parseSingleForkPage(a,
d,c,b)},parseFieldset:function(a,d,c,b){var e=b.data.attr,k=j.layout.fieldset,g=p.cutTagHeadSpace(b.data.content).replace(/<\/legend>[\s]+/,"</legend>").replace(/<legend([^>]*)>(.+)<\/legend>/,"\n<label$1>$2</label>\n");e.border=k.border||1;e["font-size"]=parseInt(e["font-size"]||Math.floor(d.fontSize*k.fontSizeRate));b.data.content=l.wrap("indent",{before:k.indentBefore,after:k.indentAfter,raw:true,theme:e.theme||"",syntax:e.syntax||""},g);e.theme="";e.syntax="";return this.parseSingleForkPage(a,
d,c,b)},parseDL:function(a,d,c,b){var e=b.data.attr,k=j.layout.dl;b.data.content=p.cutTagHeadSpace(b.data.content);if(k.indentBefore>0||k.indentAfter>0)e.border=0,b.data.content=l.wrap("indent",{before:k.indentBefore,after:k.indentAfter},b.data.content);return this.parseSingleForkPage(a,d,c,b)},parseDT:function(a,d,c,b){var e=j.layout.dl.dt,k=b.data.attr;k["font-size"]=parseInt(k["font-size"]||Math.floor(d.fontSize*e.fontSizeRate));b.data.content=p.cutTagHeadSpace(b.data.content);b.data.content=l.wrap("strong",
{},b.data.content);return this.parseSingleForkPage(a,d,c,b)},parseDD:function(a,d,c,b){var e=j.layout.dl.dd,k=b.data.attr;k["font-size"]=parseInt(k["font-size"]||Math.floor(d.fontSize*e.fontSizeRate));b.data.content=p.cutTagHeadSpace(b.data.content);b.data.content=l.wrap("indent",{before:e.indentBefore,after:e.indentAfter},b.data.content);return this.parseSingleForkPage(a,d,c,b)},parseSingleForkPage:function(h,f,c,b){var e=b.data.content,b=b.data.attr;t.init(b,{"margin-before":0,"margin-after":0,
border:0,"font-size":f.fontSize},b);b.border=parseInt(b.border);b["margin-before"]=parseInt(b["margin-before"]);b["margin-after"]=parseInt(b["margin-after"]);var h=c.getRestLineSpace(f),k=b["margin-before"]+b["margin-after"],g=f.isVertical?h:f.maxNextChar-k,k=f.isVertical?f.maxNextChar-k:h,o=b.theme?F[b.theme]:null,e=new y(e),g=new u({direction:f.direction,width:g,height:k,theme:o,fontSize:parseInt(b["font-size"])}),e=new a(e,g);e.args=b;e.forked=true;e.parent=this;f.getProp("max-next-line");b=[h];
this.aligned&&b.push(this.parent.layout.maxNextLine-(f.maxNextLine+this.offset));this.forkset=new d(b);this.forkset.add(e);return this.forkset.yieldPage(f,c)},parseTextset:function(a,d,c,b){var e=b,k=j.layout.textset;for(e.childs=[];;)if(b=a.getToken(),b.type=="tag"){var g=b.data.name,o=b.data.attr;if(g=="/textset")break;if(g=="tpart")o.scale=parseFloat(o.scale||k.tpart.fontSizeRate),e.childs.push(b.data)}return this.parseSetForkPage(a,d,c,e)},parseUL:function(a,d,c,b){var e=b.data.attr,k=j.layout.ul,
g=b.data.content.replace(/[\s]+(<\/?li)/gi,"$1");e.border=0;b.data.content=l.wrap("indent",{before:k.indentBefore,after:k.indentAfter},g);this.liCount=1;return this.parseSingleForkPage(a,d,c,b)},parseLI:function(a,d,c,b){var e={childs:[]},k=this.parent.parent.forktag,g=j.layout[k]||j.layout.ul,o=g.li,b=b.data,o=parseFloat(b.attr.scale||o.fontSizeRate),v=Math.floor(d.fontSize*o);this.liIndex=this.parent.parent.liCount++;k=="ol"?d.isVertical?(g=v+v,k="<pack>"+this.liIndex+"</pack>&nbsp;"):(g=Math.floor(v*
2.5),k=this.liIndex+".&nbsp;"):(k=g.listMark,g=v);k={content:k,attr:{scale:o,size:g}};b.attr.scale=o;b.content=p.cutEdgeCRLF(b.content);e.childs.push(k);e.childs.push(b);return this.parseSetForkPage(a,d,c,e)},parseScenario:function(a,d,c,b){var e=b,k={},g=j.layout.scenario;for(e.childs=[];;)if(b=a.getToken(),b.type=="tag"){var b=b.data,o=b.name,v=b.attr;if(o=="/scenario")break;switch(o){case "sbody":var D=Math.floor(d.fontSize*g.sbody.marginRate);v.scale=parseFloat(v.scale||g[o].fontSizeRate);b.args=
{};b.args["margin-before"]=D;b.args["margin-after"]=D;k[o]=b;break;case "shead":case "sfoot":v.scale=parseFloat(v.scale||g[o].fontSizeRate),v.size=parseInt(v.size||g[o].size),k[o]=b}}g=["shead","sbody","sfoot"];for(b=0;b<g.length;b++)o=g[b],k[o]&&e.childs.push(k[o]);return this.parseSetForkPage(a,d,c,e)},parseSetForkPage:function(h,f,c,b){var e=this,h=b.childs,b=m.filter(h,function(a){return typeof a.attr.size!="undefined"}),k=m.fold(b,0,function(a,b){return a+parseInt(b.attr.size)}),g=Math.floor(((f.isVertical?
f.height:f.width)-k)/(h.length-b.length)),o=c.getRestLineSpace(f),j=function(b,c,d,h){b=new a(new y(b),new u({direction:f.direction,width:f.isVertical?o:c,height:f.isVertical?c:o,fontSize:d}));b.args=h;b.parent=e;return b},b=[o];this.aligned&&b.push(this.parent.layout.maxNextLine-(f.maxNextLine+this.offset));this.forkset=new d(b);b=0;for(k=h.length;b<k;b++)(function(a){var b=parseInt(a.attr.size||g);a.args=a.args||{};b-=a.args["margin-before"]||0;b-=a.args["margin-after"]||0;var c=Math.floor(parseFloat(a.attr.scale||
1)*f.fontSize);e.forkset.add(j(a.content,b,c,a.args))})(h[b]);return this.forkset.yieldPage(f,c)},parseForkPageTag:function(a,d,c,b){a.stepPos();a.skipCRLF();switch(b.data.name){case "indent":return this.parseIndent(a,d,c,b);case "blockquote":return this.parseBlockquote(a,d,c,b);case "ul":return this.parseUL(a,d,c,b);case "ol":return this.parseUL(a,d,c,b);case "li":return this.parseLI(a,d,c,b);case "dl":return this.parseDL(a,d,c,b);case "dt":return this.parseDT(a,d,c,b);case "dd":return this.parseDD(a,
d,c,b);case "fieldset":return this.parseFieldset(a,d,c,b);case "textset":return this.parseTextset(a,d,c,b);case "scenario":return this.parseScenario(a,d,c,b)}return null},parseEndPage:function(a){this.aligned||(a.stepPos(),a.skipUntilCRLF());throw"EndPage";},parseElement:function(a,d,c){if(this.forkset!=null&&this.forkset.hasNext())return this.forkset.yieldPage(d,c);try{var b=a.lookToken();c.seekTextPos=b.pos;b=this.onParseElementBefore(a,d,c,b)}catch(e){return null}if(q.isEndPageToken(b))return this.parseEndPage(a,
d,c,b);if(q.isBlockToken(b))return this.parseBlockTag(a,d,c,b);return q.isForkPageToken(b)?(this.forktag=b.data.name,this.parseForkPageTag(a,d,c,b)):this.parseLine(a,d,c)},parsePage:function(a){var d=this.ctx.createPage(this.layout.direction,this.layout.width,this.layout.height,[]);t.copy(d,{size:0,no:this.ctx.seekPageNo,head:this.ctx.seekPageNo==0,spos:this.ctx.seekTextPos,cpos:this.ctx.seekCharCount});t.copy(d,a||{});try{for(;;){var c=this.lexer.getPos(),b=this.ctx.snap(),e=this.parseElement(this.lexer,
this.layout,this.ctx);if(e==null)throw this.finish=d.tail=true,"EndPage";else this.pushElementToPage(this.lexer,this.layout,this.ctx,d,e)}}catch(k){k=="Overflow"?(this.lexer.setPos(c),this.ctx.restoreSnap(b),this.ctx.seekNextLine=0):k=="EndPage"&&(this.ctx.seekNextLine=0);if(this.pushBlocks.length>0)d.childs=d.childs.concat(this.pushBlocks),d.size+=m.fold(this.pushBlocks,0,function(a,b){return a+b.push_size}),this.pushBlocks=[];if(typeof this.aligned=="undefined")d.topicPath=p.clone(this.ctx.topicPath),
this.ctx.seekPageNo++;return d}}};return a}(),H=function(){function d(){this.tags=[];this.ireaders=[]}d.prototype={getInlineReader:function(a){return this.ireaders[a]},pushInlineReader:function(a){var d=this.ireaders.length;this.ireaders.push(a);return d},clearInlineReaders:function(){this.ireaders=[]},pushTag:function(a){this.tags.push(a)},popTag:function(a){B.prototype.popTag.call(this,a)},findTag:function(a){return m.find(this.tags,function(d){return d.name==a})}};return d}(),N=function(){function d(a,
b){this.layout=a;this.ctx=typeof b!="undefined"?b:new H;this.handlers={}}var a=function(a,b){var c={};if(typeof b.scale!="undefined"){var e=Math.floor(b.scale*a.fontSize);c["font-size"]=e+"px";c["line-height"]=e+"px"}if(typeof b.family!="undefined")c["font-family"]=b.family;if(typeof b.weight!="undefined")c["font-weight"]=b.weight;if(typeof b.color!="undefined")c.color=b.color;return c},g=function(a,b){var c=b.stepSize;return{clear:"both",height:c+"px","line-height":c+"px"}},h=function(a,b){var c=
Math.floor(b.fontSize*b.hscaleImg),c={width:b.fontSize+"px",height:c+"px","line-height":c+"px"};typeof b["margin-before"]!="undefined"&&(c[a.getCssProp("margin-before")]=b["margin-before"]+"px");typeof b["margin-after"]!="undefined"&&(c[a.getCssProp("margin-after")]=b["margin-after"]+"px");return c},f=function(a,b){var c=b.data,e=Math.floor(b.fontSize/2),d=typeof b["margin-before"]!="undefined"?b["margin-before"]:0,f=typeof b["margin-after"]!="undefined"?b["margin-after"]:0;c.length>2&&(f+=e*(c.length-
2));return{"margin-top":d+"px","margin-bottom":f+"px","-webkit-transform":"rotate(90deg)","-webkit-transform-origin":"50% 50%","-moz-transform":"rotate(90deg)","-moz-transform-origin":"50% 50%","-o-transform":"rotate(90deg)","-o-transform-origin":"50% 50%"}},c=function(a,b){var c={"float":a.getCssProp("block-float"),width:b.width+"px",height:b.height+"px",margin:0,padding:0};b["margin-prev"]&&(c[a.getCssProp("margin-prev")]=b["margin-prev"]+"px");return c},b=function(a,b){var c={"float":a.getCssProp("block-float"),
width:b.width+"px",height:b.height+"px","border-width":b.border+"px",margin:0,padding:0};b["margin-prev"]&&(c[a.getCssProp("margin-prev")]=b["margin-prev"]+"px");return c},e=function(a,b,c){a={width:"100%","font-size":c.fontSize+"px","line-height":c.fontSize+"px","float":"left","text-align":"center",padding:0};typeof c["margin-bottom"]!="undefined"&&(a["margin-bottom"]=c["margin-bottom"]+"px");typeof c["margin-top"]!="undefined"&&(a["margin-top"]=c["margin-top"]+"px");typeof c["text-align"]!="undefined"&&
(a["text-align"]=c["text-align"]);return a},k=function(a,b,c){a={position:"absolute","font-size":c.fontSize+"px","line-height":c.fontSize+"px"};a["margin-left"]=c.position.x+"px";a["margin-top"]=c.position.y+"px";a["text-align"]="left";return a},s=function(a,b){var c=a.isVertical?b.fontSize:b.textLineSize.height,c={display:"block","float":a.getCssProp("block-float"),"text-align":a.getCssProp("line-text-align"),"font-size":b.fontSize+"px",width:b.textLineSize.width+"px",height:b.textLineSize.height+
"px","line-height":c+"px"};x.isIE&&a.isVertical&&(c.overflow="hidden");return c},o=function(a,b){var c=a.isVertical?b.fontSize:b.rubyLineSize.height;return{display:"block","float":a.getCssProp("block-float"),width:b.rubyLineSize.width+"px",height:b.rubyLineSize.height+"px","line-height":c+"px"}},v=function(a,b){var c={display:"block",overflow:"visible","float":a.getCssProp("block-float"),width:b.width+"px",height:b.height+"px"};x.isMobileSafari&&(c["letter-spacing"]="-0.001em");return c},D=function(a,
b){var c=v(a,b);b.attr["background-color"]&&(c["background-color"]=b.attr["background-color"]);c[a.isVertical?"height":"width"]="100%";return c},T=function(a,b){var c={"font-size":b.fontSize+"px","text-align":a.isVertical?"center":"left","line-height":b.fontSize+"px"};a.isVertical||(c.height=b.fontSize+"px");c[a.getCssProp("margin-before")]=b.textSpaceBefore+"px";c[a.getCssProp("margin-after")]=b.textSpaceAfter+"px";a.isVertical||(c["margin-top"]=Math.floor((b.height-b.fontSize)/2)+"px");b.attr.color&&
(c.color=b.attr.color);return c},R=function(a,b){var c={};b.head||(c[a.getCssProp("border-prev")]="none");b.tail||(c[a.getCssProp("border-next")]="none");return c},S=function(a,b){var c={display:"block","float":b["float"]||a.getCssProp("block-float"),width:b.width+"px",height:b.height+"px"};b.size&&(c[a.getCssProp("page-size")]=b.size+"px");b["margin-before"]&&(c[a.getCssProp("margin-before")]=b["margin-before"]+"px");b["margin-after"]&&(c[a.getCssProp("margin-after")]=b["margin-after"]+"px");b["margin-prev"]&&
(c[a.getCssProp("margin-prev")]=b["margin-prev"]+"px");b.border&&(c["border-width"]=b.border+"px",b.forked&&t.copy(c,R(a,b)));return c};d.prototype={getContext:function(){return this.ctx},setOutputHandler:function(a,b){this.handlers[a]=b},callOutputHandler:function(a,b,c,e,d,f){return typeof this.handlers[a]!="undefined"?this.handlers[a](b,c,e,d,f):f},evalChar:function(a,b,c,e){if(e.src)return this.evalCharIcon(a,b,c,e);else if(a.isVertical)return e.img?this.evalCharImgVertical(a,b,c,e):this.evalCharVertical(a,
b,c,e);return this.evalCharHorizontal(a,b,c,e)},evalWord:function(a,b,c,e){return a.isVertical?this.evalWordVertical(a,b,c,e):e.data},evalTcy:function(a,b,c,e){return a.isVertical?e.data+"<br />":e.data},evalCharVertical:function(a,b,c,e){a=typeof e.cnv!="undefined"?e.cnv:e.data;return e.skana?l.wrap("div",{style:n.css({"font-size":e.fontSize+"px",overflow:"visible",position:"relative",top:"-0.2em",right:"-0.12em",height:e.stepSize+"px","line-height":e.stepSize+"px"})},a):a=="&nbsp;"?l.wrap("div",
{style:n.css({"line-height":"0.5em",height:"0.5em"})},a):a+"<br />"},evalCharHorizontal:function(a,b,c,e){a=e.data;return a==" "?"&nbsp;":a},evalCharIcon:function(a,b,c,e){b=l.start("img",{"class":j.className.charIcon,width:e.width+"px",height:e.height+"px",style:n.css({}),src:e.src});return a.isVertical?b+"<br />":b},evalCharImgVertical:function(a,b,c,e){return l.wrap("div",{"class":j.className.charImg,style:n.css(g(a,e))},l.start("img",{src:r.ofImgSrc(e.img,e.color),style:n.css(h(a,e))}))},evalWordVertical:function(a,
b,c,e){return l.wrap("div",{style:n.css(x.isIE?{"writing-mode":"tb-rl","line-height":e.fontSize+"px"}:f(a,e))},e.data)},evalRubyBodyVert:function(a,b,c,e){a=e.data.length*e.fontSize;b=new y(e.data);a=new u({width:e.fontSize,height:a,fontSize:e.fontSize,enableRuby:false,disableTailSpace:true});c=new B(a);b=(new G(b,a)).parseLine(b,a,c);c=new H;return this.evalTextLineBody(a,c,e,b)},evalRubyBody:function(a,b,c,e){return/vertical/.test(e.direction)?this.evalRubyBodyVert(a,b,c,e):e.data},evalRuby:function(a,
b,c,e){return l.wrap("div",{"class":j.className.rubyText,style:n.css(k(a,c,e))},this.evalRubyBody(a,b,c,e))},evalCaption:function(a,b,c,d){return l.wrap("div",{"class":[j.className.caption,d.captionPos].join(" "),style:n.css(e(a,c,d))},p.escape(d.data))},evalStartLineTags:function(a,b,c){var e=this;return m.fold(b.tags,"",function(d,f){return f.name=="font"?d+e.evalFontStartBody(a,b,c,f):d+l.start(f.name,f.attr)})},evalCloseLineTags:function(a,b,c){var e=this;return m.fold(b.tags,"",function(d,f){return f.name==
"font"?d+e.evalFontEndBody(a,b,c,f):d+l.end(f.name)})},evalRubyLine:function(a,b,c,e){if(e.rubyLineSize.width==0||e.rubyLineSize.height==0)return"";var d=this,c=[j.className.rubyLine,a.direction].join("-");return l.wrap("div",{"class":[j.className.rubyLine,c].join(" "),style:n.css(o(a,e))},m.fold(e.rubyList,"",function(c,f){return c+d.evalRuby(a,b,e,f)}))},evalTextLineBody:function(a,b,c,e){var d=this;return this.callOutputHandler("onCompleteTextLineBody",a,b,c,e,[this.evalStartLineTags(a,b,c,e),
m.fold(e.childs,"",function(c,f){return c+d.evalElement(a,b,e,f)}),this.evalCloseLineTags(a,b,c,e)].join(""))},evalTextLine:function(a,b,c,e){var d=[j.className.textLine,a.direction].join("-");return l.wrap("div",{"class":[j.className.textLine,d].join(" "),style:n.css(s(a,e))},this.evalTextLineBody(a,b,c,e))},evalLineSet:function(a,b,c,e){return a.enableRuby?[this.evalRubyLine(a,b,c,e),this.evalTextLine(a,b,c,e)].join(""):this.evalTextLine(a,b,c,e)},evalLine:function(a,b,c,e){return l.wrap("div",
{"class":j.className.line,style:n.css(v(a,e))},this.evalLineSet(a,b,c,e))},evalLabelLine:function(a,b,c,e){return l.wrap("div",{"class":j.className.labelLine,style:n.css(D(a,e))},l.wrap("div",{"class":j.className.labelLineBody,style:n.css(T(a,e))},this.evalTextLineBody(a,b,c,e)))},evalImgBody:function(a,b,c,e){a=b.findTag("a");e=l.start("img",{src:e.src,width:e.width,height:e.height,style:n.css({"border-width":e.border+"px"})});return a!=null?l.wrap("a",a.attr,e):e},evalImg:function(a,b,e,d){return l.wrap("div",
{"class":j.className.img,style:n.css(c(a,d))},this.evalImgBody(a,b,e,d))},evalBlock:function(a,c,e,d){if(d.name=="img")return this.evalImg(a,c,e,d);a={"class":j.className.blockElement,style:n.css(b(a,d))};if(d.name=="iframe")a.src=d.src,a.frameborder=d.frameborder,a.width=d.width,a.height=d.height;else if(d.name=="textarea")a.onclick=d.onclick;return l.wrap(d.name,a,d.content)},evalInlineReader:function(a,c,e,d){c=c.pushInlineReader(d);return l.wrap("div",{"class":[j.className.inlineReader,"ireader-"+
c].join(" "),style:n.css(b(a,d))},"")},evalLinkStart:function(a,b,c,e){a=e.attr;a.href=a.href||"";if(a.href.substring(0,1)=="#")a["class"]=j.className.tocLink;b.pushTag(e);return l.start(e.name,e.attr)},evalLinkEnd:function(a,b,c,e){a=e.name.substring(1);b.popTag(a);return l.end(a)},evalBoldStart:function(a,b,c,e){b.pushTag(e);return l.start(e.name,e.attr)},evalBoldEnd:function(a,b,c,e){a=e.name.substring(1);b.popTag(a);return l.end(a)},evalFontStart:function(a,b,c,e){b.pushTag(e);return this.evalFontStartBody(a,
b,c,e)},evalFontStartBody:function(b,c,e,d){return l.start(b.isVertical?"div":"span",{style:n.css(a(b,d.attr))})},evalFontEnd:function(a,b,c,e){b.popTag("font");return this.evalFontEndBody(a,b,c,e)},evalFontEndBody:function(a){return a.isVertical?l.end("div"):l.end("span")},evalTag:function(a,b,c,e){e=e.data;switch(e.name){case "a":return this.evalLinkStart(a,b,c,e);case "/a":return this.evalLinkEnd(a,b,c,e);case "b":case "strong":return this.evalBoldStart(a,b,c,e);case "/b":case "/strong":return this.evalBoldEnd(a,
b,c,e);case "font":return this.evalFontStart(a,b,c,e);case "/font":return this.evalFontEnd(a,b,c,e)}return""},evalElement:function(a,b,c,e){switch(e.type){case "char":return this.evalChar(a,b,c,e);case "rb":return this.evalChar(a,b,c,e);case "word":return this.evalWord(a,b,c,e);case "tcy":return this.evalTcy(a,b,c,e);case "line":return this.evalLine(a,b,c,e);case "label-line":return this.evalLabelLine(a,b,c,e);case "caption":return this.evalCaption(a,b,c,e);case "ruby":return this.evalRuby(a,b,c,
e);case "block":return this.evalBlock(a,b,c,e);case "ireader":return this.evalInlineReader(a,b,c,e);case "tag":return this.evalTag(a,b,c,e);case "page":return(new d(new u({width:e.width,height:e.height,fontSize:a.fontSize,direction:e.direction||a.direction}),b)).evalPage(e)}return""},evalPage:function(a,b){var c=this,e=[];t.copy(a,b||{});a.forked?e.push(j.className.forkedPage):a.aligned?e.push(j.className.alignedPage):e.push(j.className.page);typeof a["class"]!="undefined"&&e.push(a["class"]);a.syntax&&
this.setOutputHandler("onCompleteTextLineBody",M[a.syntax].editLine);return l.wrap("div",{"class":e.join(" "),style:n.css(S(this.layout,a))},m.fold(a.childs,"",function(b,e){return b+c.evalElement(c.layout,c.ctx,a,e)}))}};return d}(),M={js:{editLine:function(d,a,g,h,f){return d.isVertical?f:f.replace(/[^:\"\'](\/\/.+)$/,"<span class='kw-cmt'>$1</span>").replace(/(\/\*[^\*]+\*\/)/,"<span class='kw-cmt'>$1</span>").replace(/(\"[^\"]+\")/g,"<span class='kw-string'>$1</span>")}},html:{editLine:function(d,
a,g,h,f){return d.isVertical?void 0:M.js.editLine(d,a,g,h,f)}}},O=function(){function d(a,d){this.lexer=new y(a);this.parser=new G(this.lexer,d);this.evaluator=new N(d)}d.prototype={hasNext:function(){return this.parser.hasNext()},getParser:function(){return this.parser},getEvaluator:function(){return this.evaluator},parsePage:function(a){return this.parser.parsePage(a)},evalPage:function(a,d){return this.evaluator.evalPage(a,d)},yieldPage:function(a){return this.evalPage(this.parsePage(a),a)}};return d}(),
P=function(){function d(a,b){this.dom=document.createElement("div");this.dom.className=c.className.screen;this.dom_s=this.dom.style;this.dom_s.width=a+"px";this.dom_s.height=b+"px";this.dom_s.margin=[c.screenSpaceTB+"px",c.screenSpaceLR+"px"].join(" ");this.dom_s.overflow="hidden";this.dom.innerHTML="<h2 class='"+c.className.loadingText+"'>LOADING...</h2>"}function a(a,b,d,f){var g=this,h=function(a){return"<span>"+a+"</span>"};this.dom=document.createElement("div");this.dom.className=c.className.pager;
this.dom_s=this.dom.style;this.dom_s.verticalAlign="middle";this.dom_s.fontSize=c.pager.fontSize+"px";this.dom_s.textAlign="center";this.dom_s.height=c.pager.height+"px";this.dom_s.lineHeight=c.pager.height+"px";this.dom_s.margin=c.pager.marginVert+"px 0";var j=document.createElement("a"),m=j.style;j.href="#btnNext";j.className=c.className.pagerNext.join(" ");j.onclick=function(){d();return false};m.width=c.pager.btnWidth+"px";var l=document.createElement("a"),I=l.style;l.href="#btnPrev";l.className=
c.className.pagerPrev.join(" ");l.onclick=function(){b();return false};I.width=c.pager.btnWidth+"px";var n=document.createElement("span");n.className=c.className.pagerStatus;n.style.width=c.pager.statusWidth+"px";this.curPage=document.createElement("input");this.curPage.className=c.className.pagerCurPage;this.curPage.type="text";this.curPage.value="0";this.curPage.style.width=c.pager.curPageInputWidth+"px";this.curPage.onkeypress=w.onkeypress(function(a){var b=g.getPageNo();a==13&&f(b)});this.pageSlash=
document.createElement("span");this.pageSlash.innerHTML="/";this.pageSlash.style.margin="0 10px";this.totalPage=document.createElement("span");this.totalPage.className=c.className.pagerTotalPage;n.appendChild(this.curPage);n.appendChild(this.pageSlash);n.appendChild(this.totalPage);a.indexOf("vertical")>=0?(j.innerHTML=h("&laquo; NEXT"),l.innerHTML=h("PREV &raquo;"),m.marginRight="16px",I.marginLeft="16px",this.dom.appendChild(j),this.dom.appendChild(n),this.dom.appendChild(l)):(j.innerHTML=h("NEXT &raquo;"),
l.innerHTML=h("&laquo; PREV"),I.marginRight="16px",m.marginLeft="16px",this.dom.appendChild(l),this.dom.appendChild(n),this.dom.appendChild(j))}function g(){this.dom=document.createElement("div");this.dom.className=c.className.footer;this.dom_s=this.dom.style;this.dom_s.textAlign="right";this.dom_s.marginRight=c.defFontSize+"px";this.dom_s.marginTop=c.footer.marginVert+"px";this.dom_s.height=c.footer.height+"px";this.dom_s.lineHeight=c.footer.height+"px";var a=document.createElement("div");a.className=
c.className.copy;a.style.fontSize="0.9em";a.innerHTML="powered by <a target='_blank' href='https://code.google.com/p/nehan/'>nehan</a> layout engine.";this.dom.appendChild(a)}function h(a,b){this.reader=a;this.offset=0;this.keyword=b}function f(a){this.nospace=typeof a.nospace!="undefined"?a.nospace:false;this.isinline=typeof a.isinline!="undefined"?a.isinline:false;this.nopager=typeof a.nopager!="undefined"?a.nopager:false;this.border=typeof a.border!="undefined"?a.border:j.layout.readerBorder;this.width=
a.width||c.defOuterWidth;this.height=a.height||c.defOuterHeight;this.screenWidth=this.width-c.screenSpaceLR*2;this.screenHeight=this.height-c.screenSpaceTB*2;this.nopager==false&&(this.screenHeight-=c.pager.height+c.pager.marginVert*2);this.isinline==false&&(this.screenHeight-=c.footer.height+c.footer.marginVert);this.pages=[];this.caches=[];this.ireaders=[];this.bookmarks=[];this.pageNo=this.progress=0;this.complete=false;this.direction=a.direction||c.defDirection;this.text=a.text||"no text";this.theme=
F[a.theme]||null;this.syntax=a.syntax||"";this.className=a.className;this.pageLayout=new u({direction:this.direction,theme:this.theme,width:this.screenWidth,height:this.screenHeight,fontSize:a.fontSize||c.defFontSize,leadingRate:a.leadingRate||c.defLeadingRate});this.generator=new O(this.text,this.pageLayout);this.onStart=a.onStart||function(){};this.onProgress=a.onProgress||function(){};this.onComplete=a.onComplete||function(){};this.onWritePageStart=a.onWritePageStart||function(){};this.onWritePageEnd=
a.onWritePageEnd||function(){}}var c={defDirection:"horizontal",defFontSize:20,defOuterWidth:600,defOuterHeight:400,defLeadingRate:1.8,screenSpaceTB:20,screenSpaceLR:32,borderWidth:1,maxSearchResult:10,maxSearchExcerptLen:20,className:{targetMarkup:"nehan-pagerize",screenWrap:"nehan-pagerize-screen-wrap",screen:"nehan-pagerize-screen",pager:"nehan-pagerize-pager",footer:"nehan-pagerize-footer",copy:"nehan-pagerize-copyright",pagerStatus:"nehan-pagerize-pager-status",pagerCurPage:"nehan-pagerize-pager-cur-page",
pagerTotalPage:"nehan-pagerize-pager-total-page",pagerNext:["nehan-button","nehan-button-orange","nehan-pagerize-pager-next"],pagerPrev:["nehan-button","nehan-button-blue","nehan-pagerize-pager-prev"],loadingText:"nehan-pagerize-loading-text"},pager:{fontSize:16,height:30,marginVert:5,btnWidth:80,statusWidth:140,curPageInputWidth:30},footer:{height:20,marginVert:5},system:{parsingLoop:20,parsingLoopIE:10,parsingSleepIE:10}},b={_findTargetNodes:function(){var a=document.getElementsByTagName("pre");
return m.filter(a,function(a){return a.className.indexOf(c.className.targetMarkup)>=0})},parseOpt:function(a){a=a||{};t.init(a,{width:c.defOuterWidth,height:c.defOuterHeight,fontSize:c.defFontSize,direction:c.defDirection},a);return a},map:function(a){var a=this.parseOpt(a),b=this._findTargetNodes();m.iter(b,function(b){var c=b.className,d=p.clone(a);d.text=b.innerHTML;if(c.indexOf("lp-horizontal")>=0)d.direction="horizontal";else if(c.indexOf("lp-vertical")>=0)d.direction="vertical";(new f(d)).start(b)})},
createReader:function(a){a=this.parseOpt(a);return new f(a)}};d.prototype={getDOM:function(){return this.dom},getInlineReaderDOMs:function(){return m.filter(this.dom.getElementsByTagName("div"),function(a){return a.className&&a.className.indexOf(j.className.inlineReader)>=0?true:false})},update:function(a){this.dom.innerHTML=a}};a.prototype={getDOM:function(){return this.dom},getPageNo:function(){return Math.max(0,parseInt(this.curPage.value)-1)},setPageNo:function(a){this.curPage.value=a},setPageCount:function(a){this.totalPage.innerHTML=
a}};g.prototype={getDOM:function(){return this.dom}};h.prototype={hasNext:function(){return this.offset>=0},getNext:function(){for(var a=this.reader,b=this.reader.getText(),d=this.keyword,f=[],h=0;h<c.maxSearchResult;h++){this.offset=b.indexOf(d,this.offset+1);if(this.offset<0)break;f.push(this.offset)}var g=function(a){return a.replace(RegExp("("+d+")","g"),function(a,b){return"<strong>"+p.escape(b)+"</strong>"})};return m.map(f,function(f){var h=a.findPageNo(f),j=a.getSourceText(h),j=c.maxSearchExcerptLen,
j=b.substring(f,f+d.length+j),j=j.replace(/<rt>[^<]+<\/rt>/g,""),j=j.replace(/<[^>]+>/g,""),j=p.escape(j),j=g(j);return{spos:f,pageNo:h,text:j}})}};f.prototype={start:function(a){this.setupUI(a);this.complete=false;this.progress=0;this.onStart(this);this.addPage(this.parsePage());this.writePage(0);if(this.pager)this.parsePageBg();else this.onComplete(this)},setupUI:function(b){var f=this;b.innerHTML="";this.dom=b;this.dom.className=[c.className.screenWrap,this.dom.className,this.className].join(" ");
this.dom_s=b.style;this.dom_s.overflow="hidden";this.dom_s.display="block";this.dom_s.width=this.width+"px";this.dom_s.height=this.height+"px";this.dom_s.borderWidth=this.border+"px";this.screen=new d(this.screenWidth,this.screenHeight);this.dom.appendChild(this.screen.getDOM());if(this.nopager==false)this.pager=new a(this.direction,function(){f.writePrev()},function(){f.writeNext()},function(a){f.writePage(a)}),this.dom.appendChild(this.pager.getDOM());if(this.isinline==false)this.footer=new g,this.dom.appendChild(this.footer.getDOM())},
resume:function(a){this.setupUI(a);this.setPageCount(this.pages.length);this.writePage(this.pageNo)},parsePage:function(){var a=this.generator.parsePage();a.syntax=this.syntax;return a},getGenerator:function(){return this.generator},getText:function(){return this.text},getDirection:function(){return this.direction},getTocs:function(){return this.generator.getParser().getContext().getTocs()},getPageNo:function(){return this.pageNo},getTotalPageCount:function(){return this.pages.length},getDOM:function(){return this.dom},
getPageJson:function(a){return this.pages[a]||null},getTopicPath:function(a){a=this.getPageJson(a);return a!=null?a.topicPath:null},getTopicPathTitle:function(a){return m.map(a,function(a){return a.title}).join("/")},makeBookmark:function(a){a=this.getPageJson(a);return a==null?null:this.getTopicPathTitle(a.topicPath)},setBookmark:function(a){var b=this.makeBookmark(a);return this.bookmarks[a]=b},deleteBookmark:function(a){this.bookmarks[a]=null},getBookmarks:function(){return this.bookmarks},getPageCache:function(a){return this.caches[a]||
null},setPageCache:function(a,b){this.caches[a]=b},setPageNo:function(a){this.pager&&this.pager.setPageNo(a)},setPageCount:function(a){this.pager&&this.pager.setPageCount(a)},getSourceText:function(a){var b=this.getPageJson(a),a=this.getPageJson(Math.max(a+1,this.pages.length-1));return b==null||a==null?"":this.text.substring(b.spos,a.spos)},findPageNo:function(a){for(var b=0,c=this.pages.length;b<c;b++){var d=this.pages[b].spos;if(d>a)return Math.max(0,b-1);else if(d==a)return b}return-1},searchKeyword:function(a){return new h(this,
a)},getSeekPos:function(a){return this.pages[a]?(a=this.pages[a],{cpos:a.cpos,spos:a.spos}):null},addPage:function(a){this.pages.push(a);return a},parsePageBg:function(){for(var a=null,b=x.isIE?c.system.parsingLoopIE:c.system.parsingLoop,d=0;d<b;d++){if(!this.generator.hasNext()){this.setPageCount(this.pages.length);this.complete=true;this.onComplete(this);return}a=this.addPage(this.parsePage())}if(a)this.progress=Math.floor(100*(a.spos||0)/this.text.length),this.setPageCount("("+this.progress+"%)"),
this.onProgress(this,this.progress,this.pages.length);var f=this;setTimeout(function(){f.parsePageBg()},x.isIE?c.system.parsingSleepIE:0)},getInlineReaderFromCache:function(a,b){return this.ireaders[a]&&this.ireaders[a][b]?this.ireaders[a][b]:null},cacheInlineReader:function(a,b,c){this.ireaders[a]||(this.ireaders[a]=[]);this.ireaders[a][b]=c},setupTocLinks:function(){var a=this,b=this.screen.getDOM().getElementsByTagName("a");m.iter(b,function(b){if(b.className==j.className.tocLink){var c=b.href.split("#");
if(c.length>0){var d=c[1];b.onclick=function(){a.writePageByTocId(d);return true}}}})},writeInlineReaders:function(a,b){var c=this,d=this.generator.getEvaluator().getContext();m.iter(b,function(b){if(b.className.match(/ireader-([\d]+)/)){var h=parseInt(RegExp.$1),g=c.getInlineReaderFromCache(a,h);g!=null?g.resume(b):(g=d.getInlineReader(h),g=new f({text:g.content,className:g["class"],direction:g.direction,fontSize:g.fontSize,width:g.width,height:g.height,theme:g.theme,syntax:g.syntax,border:g.border,
nopager:g.nopager,isinline:true}),g.child=true,g.start(b),c.cacheInlineReader(a,h,g))}})},writePageByTocId:function(a){var b=m.find(this.getTocs(),function(b){return b.id==a});b!=null&&this.writePage(b.pageNo)},writePageWithCache:function(a){var b=this.getPageJson(a);if(b!=null){var c=this.getPageCache(a);c==null&&(c=this.generator.evalPage(b),this.setPageCache(a,c));this.setPageNo(a+1);this.screen.update(c);this.writeInlineReaders(a,this.screen.getInlineReaderDOMs());this.setupTocLinks()}},writePage:function(a){(a>=
this.pages.length||a<0)&&alert("pageNo("+a+") is not available for this book");this.pageNo=a;this.onWritePageStart(this,a);this.writePageWithCache(a);this.onWritePageEnd(this,a)},writeNext:function(){this.pageNo<this.pages.length-1&&this.writePage(this.pageNo+1)},writePrev:function(){this.pageNo>0&&this.writePage(this.pageNo-1)}};b.pgconfig=c;return b}(),U=function(){var d=function(a,b,d){var f=document.createElement("a");f.href="#"+a;f.innerHTML=b;f.onclick=function(){d.writePage(a);return true};
return f},a=function(a,b,e){var f=document.createElement("table"),g=document.createElement("thead"),h=document.createElement("tr"),j=document.createElement("th"),l=document.createElement("th"),m=document.createElement("th"),n=document.createElement("tbody");f.className="nehan-book-bmark-table";f.style.borderCollapse="collapse";j.innerHTML="topic path";l.innerHTML="page";m.innerHTML="delete";h.appendChild(j);h.appendChild(l);h.appendChild(m);g.appendChild(h);f.appendChild(g);f.appendChild(n);a.appendChild(f);
var p=function(a,b){var c=document.createElement("tr"),f=document.createElement("td"),g=document.createElement("td"),h=document.createElement("td"),j=d(a,b,e),k=document.createElement("a");k.href="#delete";k.innerHTML="delete";k.onclick=function(){e.deleteBookmark(a);n.removeChild(c);return false};f.appendChild(j);g.innerHTML=a+1;h.appendChild(k);c.appendChild(f);c.appendChild(g);c.appendChild(h);return c};b.onclick=function(){var a=e.getPageNo(),b=e.setBookmark(a);bmark!=null&&(a=p(a,b),n.appendChild(a));
return false}},g=function(a,b,d,f){var g=function(a){a!=""&&(a=f.searchKeyword(a),h(d,f,a))};a.onkeypress=w.onkeypress(function(b){b==13&&g(a.value)});b.onclick=function(){g(a.value);return false}},h=function(a,b,d){a.innerHTML="";a.style.overflow="hidden";var f=d.getNext();if(f.length==0)a.innerHTML="<p>not found</p>";else{var g=function(){var f=document.createElement("p"),g=document.createElement("a");g.href="#more";g.innerHTML="more result";g.onclick=function(){h(a,b,d);return false};f.appendChild(g);
return f},j=function(a){var c=document.createElement("tr"),d=document.createElement("td"),e=document.createElement("a");e.innerHTML="p"+(a.pageNo+1);e.href="#"+a.pageNo;e.onclick=function(){b.writePage(a.pageNo);return false};d.appendChild(e);e=document.createElement("td");e.innerHTML=a.text;c.appendChild(d);c.appendChild(e);return c},l=function(){var a=document.createElement("table"),b=document.createElement("thead"),c=document.createElement("tr"),d=document.createElement("th");d.innerHTML="page";
var e=document.createElement("th");e.innerHTML="text";c.appendChild(d);c.appendChild(e);b.appendChild(c);a.appendChild(b);return a}(),n=document.createElement("tbody");l.appendChild(n);m.iter(f,function(a){n.appendChild(j(a))});f=function(){var b=document.createElement("p"),d=document.createElement("a");d.innerHTML="clear search result";d.href="#clear";d.onclick=function(){a.innerHTML="";return false};b.appendChild(d);return b}();a.appendChild(f);a.appendChild(l);d.hasNext()&&(g=g(),a.appendChild(g))}},
f=function(a,b,d){a.innerHTML="";d=b.getTopicPath(d);if(d!=null){var f=Math.max(0,d.length-1);m.iteri(d,function(d,e){var g=document.createElement("a");g.innerHTML=e.title;g.href="#"+e.pageNo;g.onclick=function(){b.writePage(e.pageNo);return false};a.appendChild(g);if(d!=f)g=document.createElement("span"),g.innerHTML="/",g.style.margin="0 0.5em",a.appendChild(g)})}};return{start:function(c){var b=new Date,e=0,h="",l=document.getElementById(c.ui.topicPathId||"topic-path"),m=document.getElementById(c.ui.tocId||
"toc"),n=document.getElementById(c.ui.searchInputId||"search-input"),p=document.getElementById(c.ui.searchBtnId||"search-btn"),t=document.getElementById(c.ui.searchResultId||"search-result"),r=document.getElementById(c.ui.bookBodyId||"book-body"),q=c.text||(r?r.innerHTML:"body text not found"),w=document.getElementById(c.ui.bmarkId||"bmark"),x=document.getElementById(c.ui.bmarkBtnId||"bmark-btn");r.innerHTML="";q=P.createReader({text:q,direction:c.direction||"horizontal",width:c.width||700,height:c.height||
600,fontSize:c.fontSize||18,onStart:function(a){if(location.href.match("#")){var b=location.href.split("#")[1];isNaN(b)?h=b:e=parseInt(b)}if(c.onStart)c.onStart(a)},onComplete:function(f){var l=(new Date-b)/1E3;if(m){var r=f.getTocs(),s=document.createElement("ul"),q=s,u=null;s.className="nehan-toc-root";for(var y=0,B=r.length;y<B;y++){var z=r[y],C=document.createElement("li"),E=d(z.pageNo,z.title||"no title",f);C.appendChild(E);if(u==null)q.appendChild(C);else if(z.level==u.level)q.appendChild(C);
else if(z.level>u.level){var u=z.level,E=document.createElement("ul"),A=j.tags.toc;E.className="nehan-toc-level-"+A[u%A.length];ul=E;ul.appendChild(C);q.appendChild(ul);q=ul}else z.level<u.level&&(q=z.level<=0?s:q.parentNode,q.appendChild(C));u=z}m.appendChild(s)}n&&p&&t&&g(n,p,t,f);w&&x&&a(w,x,f);if(c.onComplete)c.onComplete(f,l);e>0?f.writePage(e):h!=""&&f.writePageByTocId(h)},onProgress:function(){},onWritePageStart:function(){window.scroll(0,0)},onWritePageEnd:function(a,b){f(l,a,b)}});if(c.onBeforeStart)c.onBeforeStart(q);
q.start(r)}}}();Nehan3.version="3.0.0";Nehan3.env=x;Nehan3.config=j;Nehan3.Pagerize=P;Nehan3.Book=U;Nehan3.Util=p;Nehan3.Closure=w;Nehan3.Args=t;Nehan3.List=m;Nehan3.Attr=n;Nehan3.Tag=l;Nehan3.Token=q;Nehan3.Char=r;Nehan3.Word=J;Nehan3.CharImgColor=K;Nehan3.Lexer=L;Nehan3.BufferedLexer=y;Nehan3.Layout=u;Nehan3.Theme=F;Nehan3.ParserContext=B;Nehan3.DocumentParser=G;Nehan3.EvalContext=H;Nehan3.NehanEvaluator=N;Nehan3.PageGenerator=O})();



