/*
 nehan3.js
 Copyright (C) 2011, 2012, Watanabe Masaki<lambda.watanabe[at]gmail.com>

 licenced under MIT licence.

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
*/

var Nehan3;Nehan3||(Nehan3={});
(function(){var k={layout:{minFontSize:10,minKerningFontSize:12,defFontSize:18,tabLength:4,defLeadingRate:1.8,rubySizeRate:0.5,captionSizeRate:0.65,captionMarginRate:1,blockMarginRate:0.8,readerBorder:1,acceptableResizeRate:0.6,headerScales:[2.4,2,1.6,1.4,1,1],indent:{indentBefore:2,indentAfter:1},blockquote:{indentBefore:2,indentAfter:1,fontSizeRate:0.9,border:1},fieldset:{indentBefore:1,indentAfter:0,fontSizeRate:0.9,border:1},textset:{tpart:{fontSizeRate:0.9}},dl:{indentBefore:0,indentAfter:0,
dt:{indentBefore:0,indentAfter:0,fontSizeRate:0.9},dd:{indentBefore:1,indentAfter:0,fontSizeRate:0.9}},ul:{indentBefore:1,indentAfter:1,listMark:"\u30fb",li:{fontSizeRate:0.9}},ol:{indentBefore:1,indentAfter:1,listMark:"\u30fb",li:{fontSizeRate:0.9}},scenario:{shead:{size:100,fontSizeRate:0.9},sfoot:{size:80,fontSizeRate:0.7},sbody:{fontSizeRate:1,marginRate:0.2}}},color:{defCharImgColor:"000000",labelCharImgColor:"FFFFFF"},className:{img:"nehan-img",line:"nehan-line",page:"nehan-page",wrap:"nehan-wrap",
charImg:"nehan-char-img",charIcon:"nehan-char-icon",forkedPage:"nehan-forked-page",alignedPage:"nehan-aligned-page",inlineReader:"nehan-inline-reader",errorMsg:"nehan-error-msg",textLine:"nehan-text-line",rubyLine:"nehan-ruby-line",labelLine:"nehan-label-line",labelLineBody:"nehan-label-line-body",rubyText:"nehan-ruby-text",caption:"nehan-caption",blockElement:"nehan-block-element",tocLink:"nehan-toc-link"},rex:{word:/[\w!\.\?\/\_:#;]+/,nvAttr:/(?:\S+)=["']?(?:(?:.(?!["']?\s+(?:\S+)=|["']))+.)["']?/g},
tags:{single:["img","br","end-page"],tcy:["pack","tcy"],greedy:["pre"],block:"img,table,iframe,textarea,ireader,ipage".split(","),fork:"blockquote,ul,ol,li,dl,dt,dd,fieldset,indent,textset,scenario".split(","),toc:["part","chapter","section","subsection"],content:"blockquote,indent,table,textarea,iframe,ipage,ireader,shead,sbody,sfoot,tpart,fieldset,ul,ol,li,dl,dt,dd".split(",")},types:{textToken:["char","tcy","word","rb"]},system:{lang:"ja-jp",nobr:false,conv_br:false,lexingBufferLen:2E3,enableYakuMetricsCheck:true,
lineBreakCheckLevel:2},charImgRoot:"http://nehan.googlecode.com/hg/char-img"},D={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS"},searchString:function(c){for(var a=0;a<c.length;a++){var h=c[a].string,f=c[a].prop;this.versionSearchString=c[a].versionSearch||c[a].identity;if(h){if(h.indexOf(c[a].subString)!=
-1)return c[a].identity}else if(f)return c[a].identity}},searchVersion:function(c){var a=c.indexOf(this.versionSearchString);return a==-1?void 0:parseFloat(c.substring(a+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera"},
{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,
subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};D.init();var r={init:function(){var c=D.browser.toLowerCase(),a=D.OS.toLowerCase(),h=navigator.userAgent;this.isIE=c=="explorer";this.isWin=a=="windows";this.isMac=a=="mac";
this.isIPhone=navigator.platform=="iPhone";this.isIPad=navigator.platform=="iPad";this.isIPod=navigator.platform=="iPod";this.isMobileSafari=this.isIPhone||this.isIPad||this.isIPod;this.isAndroid=/android/.test(h)}};r.init();var t={clone:function(c){var a;if(typeof c=="object")if(c instanceof Array){a=[];for(var h=0,f=c.length;h<f;h++)a[h]=this.clone(c[h])}else for(prop in a={},c)a[prop]=this.clone(c[prop]);else a=c;return a},cutQuote:function(c){return c.replace(/\"/g,"").replace(/\'/g,"")},cutTagHeadSpace:function(c){return c.replace(/[\s]+</g,
"<")},cutHeadSpace:function(c){return c.replace(/^[\s]+/,"")},cutHeadCRLF:function(c){return c.replace(/^\n+/g,"")},cutTailCRLF:function(c){return c.replace(/\n+$/g,"")},cutEdgeCRLF:function(c){return this.cutTailCRLF(this.cutHeadCRLF(c))},escape:function(c){return c.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/'/g,"&#039;").replace(/"/g,"&quot;")},filenameConcat:function(c,a){c=c==""?"":c.slice(-1)=="/"?c:c+"/";a=a==""?"":a[0]=="/"?a.substring(1,a.length):a;return c+a}},
x={eq:function(c){return function(a){return c==a}},onkeypress:function(c){return function(a){c(r.isIE?event.keyCode:a.keyCode||a.which)}}},q={copy:function(c,a){for(prop in a)c[prop]=a[prop];return c},init:function(c,a,h){for(prop in a)c[prop]=typeof h[prop]=="undefined"?a[prop]:h[prop];return c}},l={iter:function(c,a){for(var h=0,f=c.length;h<f;h++)a(c[h])},iteri:function(c,a){for(var h=0,f=c.length;h<f;h++)a(h,c[h])},map:function(c,a){for(var h=[],f=0,j=c.length;f<j;f++)h.push(a(c[f]));return h},
fold:function(c,a,h){for(var f=0,j=c.length;f<j;f++)a=h(a,c[f]);return a},filter:function(c,a){for(var h=[],f=0,j=c.length;f<j;f++){var d=c[f];a(d)&&h.push(d)}return h},find:function(c,a){for(var h=0,f=c.length;h<f;h++){var j=c[h];if(a(j))return j}return null},exists:function(c,a){return this.find(c,a)!=null}},s={html:function(c){var a=[];for(prop in c){var h=c[prop]+"",h=t.escape(h);c[prop]!=""&&a.push(prop+"='"+h+"'")}return a==[]?"":a.join(" ")},css:function(c){var a=[];for(prop in c){var h=c[prop]+
"",h=t.escape(h);a.push(prop+":"+h+";")}return a.join("")}},m={isStartTagName:function(c){return c.charAt(0)!="/"},isTcyTagName:function(c){return l.exists(k.tags.tcy,x.eq(c))},isSingleTagName:function(c){return l.exists(k.tags.single,x.eq(c))},isBlockTagName:function(c){return l.exists(k.tags.block,x.eq(c))},isForkPageTagName:function(c){return l.exists(k.tags.fork,x.eq(c))},isContentTagName:function(c){return l.exists(k.tags.content,x.eq(c))},start:function(c,a){var h="<"+c;if(typeof a!="undefined"||
a==null)var f=s.html(a),h=f!=""?[h,f].join(" "):h;h+=this.isSingleTagName(c)?" />":">";return h},wrap:function(c,a,h){return[this.start(c,a),h,"</"+c+">"].join("")},end:function(c){return"</"+c+">"}},u={isCharCountableToken:function(c){return!this.isTextToken(c)?false:/\s/.test(c.data)?false:c.type=="char"&&c.img?false:true},isEndPageToken:function(c){return c.type=="tag"&&c.data.name=="end-page"},isTextToken:function(c){return l.exists(k.types.textToken,x.eq(c.type))},isBlockToken:function(c){return c.type!=
"tag"?false:m.isBlockTagName(c.data.name)},isForkPageToken:function(c){return c.type!="tag"?false:m.isForkPageTagName(c.data.name)}},J={isTcy:function(c){return c.length!=2?false:c=="!!"||c=="!?"||c=="??"?true:c.match(/\d\d/)!=null}},o={isHeadNg:function(c){return/[\uff09\)\u300d\u3011\u3015\uff3d\]\u3002\u300f\uff1e\u3009\u300b\u3001\uff0e\.,]/.test(c)},isTailNg:function(c){return/[\uff08\(\u300c\u3010\uff3b\u3014\u300e\uff1c\u3008\u300a]/.test(c)},isTailConnectiveChar:function(c){return/[\u3001\u3002\.\uff0e,\uff0c\u300d\u300f\uff09]/.test(c)},
isKakkoStartChar:function(c){return/[\u300c\u300e\u3010\uff3b\uff08\u300a\u3008\u226a\uff1c\uff5b{\[\(]/.test(c)},isKakkoEndChar:function(c){return/[\u300d\u300f\u3011\uff3d\uff09\u300b\u3009\u226b\uff1e\uff5d}\]\)]/.test(c)},isKutenTouten:function(c){return/[\u3001\u3002,.]/.test(c)},isZenkaku:function(c){return escape(c).charAt(1)=="u"},isHankaku:function(c){return!this.isZenkaku(c)},isSmallKana:function(c){c=c.charCodeAt(0);return l.exists([12353,12355,12357,12359,12361,12387,12419,12421,12423,
12430,12449,12451,12453,12455,12457,12483,12515,12517,12519,12526,12533,12534],x.eq(c))},ofImgSrc:function(c,a){a=typeof a!="undefined"?a:k.color.defCharImgColor;return t.filenameConcat(k.charImgRoot,c+"/"+a+".png")}},Q={getLevel:function(c){for(var a=k.tags.toc,h=0,f=a.length;h<f;h++)if(a[h]==c)return h;return 0}},K={RG:[0,36,73,109,146,182,219,255],B:[0,85,170,255],namedColors:{black:{r:0,g:0,b:0},red:{r:256,g:0,b:0},green:{r:0,g:256,b:0},blue:{r:0,g:0,b:256},white:{r:256,g:256,b:256}},findNear:function(c,
a){if(c==0||c==255)return c;for(var h=256,f=0,j=0;j<a.length;j++){var d=Math.abs(c-a[j]);d<h&&(h=d,f=a[j])}return f},get:function(c){c=c.replace("#","").toLowerCase();if(c=="000000"||c=="000"||c=="black")return"000000";if(c=="ffffff"||c=="fff"||c=="white")return"FFFFFF";if(this.namedColors[c])var a=this.namedColors[c],h=a.r,f=a.g,a=a.b;else if(/[^0-9a-f]/.test(c))return"000000";else c.length==3?(h=parseInt([c[0],c[0]].join(""),16),f=parseInt([c[1],c[1]].join(""),16),a=parseInt([c[2],c[2]].join(""),
16)):c.length==6&&(h=parseInt(c.substring(0,2),16),f=parseInt(c.substring(2,4),16),a=parseInt(c.substring(4,6),16));h=this.findNear(h,this.RG);f=this.findNear(f,this.RG);a=this.findNear(a,this.B);c=function(f){return f.length<=1?"0"+f:f};h=c(h.toString(16));f=c(f.toString(16));a=c(a.toString(16));return(h+f+a).toUpperCase()}},L=function(){function c(b){this.text=this._preprocess(b);this.pos=0;this.rb=""}var a=function(b,d){var e=b.indexOf(">",d+1);return e<0?"":b.substring(d,e+1)},h=function(b){b=
b.split(/\s+/);b.shift();return l.map(b,function(b){return b.replace(/=.+/,"")})},f=function(b){var d={},b=b.match(k.rex.nvAttr);if(b==null)return d;l.iter(b,function(b){if(b.match(/([\w\-]+)=(.+)/)){var b=RegExp.$1.toLowerCase(),e=t.cutQuote(RegExp.$2);d[b]=e}});return d},j=function(b){var b=b.replace(/[\s]+=[\s]+/g,"="),d=h(b),e=f(b);l.iter(d,function(b){typeof e[b]=="undefined"&&(e[b]=true)});return e},d=function(b){var d=b.replace("<","").replace("/>","").replace(">",""),b=d.split(/[\s\t\u3000]+/)[0].toLowerCase(),
d=j(d);return{type:"tag",data:{name:b,attr:d}}},b=function(d,e,f){var a=d.indexOf("</"+e,f),f=d.indexOf("<"+e,f);return a<0?-1:f<0||a<f?a:b(d,e,a+1)},e=function(d,e,f){e=b(d,e,f);return d.substring(f,e)};c.prototype={_preprocess:function(b){for(var d="",e=0;e<k.layout.tabLength;e++)d+="&nbsp;";b=b.replace(/(\t)/,function(){return d}).replace(/<([\w\-]+)/g,function(b,d){return"<"+d.toLowerCase()}).replace(/<\/([\w\-]+)/g,function(b,d){return"</"+d.toLowerCase()}).replace(/([^\n])<img/g,"$1\n<img").replace(/([^\n])<table/g,
"$1\n<table").replace(/([^\n])<end-page/g,"$1\n<end-page").replace(/([^\n])<blockquote/g,"$1\n<blockquote").replace(/([^\n])<indent/g,"$1\n<indent").replace(/([^\n])<iframe/g,"$1\n<iframe").replace(/([^\n])<ipage/g,"$1\n<ipage").replace(/([^\n])<ireader/g,"$1\n<ireader");k.system.conv_br?b=b.replace(/<br>/gi,"\n").replace(/<br \/>/gi,"\n"):k.system.nobr&&(b=b.replace(/<br>/gi,"").replace(/<br \/>/gi,""));return b},_lookChar:function(b){b=this.pos+(b||0);if(b==this.text.length)return"\n";if(b>this.text.length)throw"BufferEnd";
return this.text.charAt(b)},_mapChar:function(b,d){var e=d.charCodeAt(0),f={type:"char",data:d,vscale:1,hscale:1,half:o.isHankaku(d),pos:b},a=function(b,d,e){f.img=b;f.vscale=d||1;f.hscale=e||f.vscale;return f},j=function(b,d,e){f.cnv=b;f.vscale=d||1;f.hscale=e||f.vscale;return f};if(o.isSmallKana(d))return f.skana=true,f;if(d==" ")return j("&nbsp;");switch(e){case 12300:return a("kakko1",0.5);case 65378:return a("kakko1",0.5);case 12301:return a("kakko2",0.5);case 65379:return a("kakko2",0.5);case 12302:return a("kakko3",
0.5);case 12303:return a("kakko4",0.5);case 65288:return a("kakko5",0.5);case 40:return a("kakko5",0.5);case 65371:return a("kakko5",0.5);case 123:return a("kakko5",0.5);case 65289:return a("kakko6",0.5);case 41:return a("kakko6",0.5);case 65373:return a("kakko6",0.5);case 125:return a("kakko6",0.5);case 65308:return a("kakko7",0.5);case 60:return a("kakko7",0.5);case 12296:return a("kakko7",0.5);case 65310:return a("kakko8",0.5);case 62:return a("kakko8",0.5);case 12297:return a("kakko8",0.5);case 12298:return a("kakko9",
0.5);case 8810:return a("kakko9",0.5);case 12299:return a("kakko10",0.5);case 8811:return a("kakko10",0.5);case 65339:return a("kakko11",0.5);case 12308:return a("kakko11",0.5);case 91:return a("kakko11",0.5);case 65341:return a("kakko12",0.5);case 12309:return a("kakko12",0.5);case 93:return a("kakko12",0.5);case 12304:return a("kakko17",0.5);case 12305:return a("kakko18",0.5);case 65306:return a("tenten",0.5,1);case 58:return a("tenten",0.5,1);case 12290:return a("kuten",0.5);case 65377:return a("kuten",
0.5);case 65294:return a("period",1);case 46:return a("period",1);case 12289:return a("touten",0.5);case 65380:return a("touten",0.5);case 44:return a("touten",0.5);case 65292:return a("touten",0.5);case 65374:return a("kara",1);case 12316:return a("kara",1);case 8230:return a("mmm",1);case 8229:return a("mm",1);case 12317:return a("dmn1",1);case 12319:return a("dmn2",1);case 65309:return a("equal",1);case 61:return a("equal",1);case 12540:return j("\uff5c");case 45:return j("\uff5c");case 8213:return j("\uff5c");
case 65293:return j("\uff5c");case 9472:return j("\uff5c");case 8593:return j("&#8594;");case 8594:return j("&#8595;");case 8658:return j("&#8595;");case 8595:return j("&#8592;");case 8592:return j("&#8593;")}return f},_mapTag:function(b,d){var e=d.data.name;return e=="ruby"?this._readRubyTag(b,d):e=="img"?this._readImgTag(b,d):m.isTcyTagName(e)?this._readTcyTag(b,d):m.isContentTagName(e)?this._readContentTag(b,d):d},_skipComment:function(b){this.pos=this.text.indexOf("--\>",b)+3},_readTag:function(b){var e=
a(this.text,b),f=d(e);f.pos=b;this.pos+=e.length;return f},_readContentTag:function(b,d){var f=e(this.text,d.data.name,this.pos);d.data.content=f;this.pos+=f.length+d.data.name.length+3;return d},_readTagGroup:function(b,f){var j=k.tags.group[f.data.name],c=e(this.text,f.data.name,this.pos);this.pos+=c.length+f.data.name.length+3;f.data.childs={};l.iter(j.childs,function(b){var j;j=c.indexOf("<"+b);if(j<0)j=null;else{var g=a(c,j);if(g=="")j=null;else{var h=d(g);h.data.content=e(c,b,j+g.length);j=
h.data}}j!=null&&(f.data.childs[b]=j)});return f},_readRubyTag:function(b,d){var f={type:"ruby",pos:b},a=e(this.text,d.data.name,this.pos);this.pos+=a.length+7;if(a.match(/<rt>([^<]+)<\/rt>/i))f.yomi=RegExp.$1;if(a.match(/<rb>([^<]+)<\/rb>/i))this.rb=f.kanji=RegExp.$1;else if(a.match(/([^<]+)<rt>/i))this.rb=f.kanji=RegExp.$1;return f},_readTcyTag:function(b,d){var f=e(this.text,d.data.name,this.pos);this.pos+=f.length+d.data.name.length+3;return{type:"tcy",data:f,pos:b}},_readImgTag:function(b,d){return d},
_readRbChar:function(b){var d=this.rb.charAt(0);this.rb=this.rb.substring(1);b=this._mapChar(b,d);b.type="rb";return b},_readSpecialChar:function(b,d){var e=this.text.substring(b).match(/&[a-zA-Z#0-9]+;/),e=e?e.toString():d;return e==""||e.length==1||e.length>10?(e=this._mapChar(b,d),this.pos++,e):(this.pos+=e.length,{type:"char",data:e,vscale:1,half:true,pos:b})},_readChar:function(b,d){var e=this._mapChar(b,d);this.pos++;return e},_readWord:function(b,d){var e=this.text.substring(b).match(k.rex.word),
e=e?e.toString():d,f=J.isTcy(e)?"tcy":"word";this.pos+=e.length;return e.length==1?this._mapChar(b,e):{type:f,data:e,pos:b}},getPos:function(){return this.pos},getToken:function(){var b=this.pos;if(this.rb!="")return this._readRbChar(b);else var d=this._lookChar();if(d=="<"){try{if(this._lookChar(1)=="!")return this._skipComment(b),this.getToken()}catch(e){}d=this._readTag(b);return this._mapTag(b,d)}else return d=="&"?this._readSpecialChar(b,d):d.match(k.rex.word)?this._readWord(b,d):this._readChar(b,
d)}};return c}(),C=function(){function c(a){this.lexer=new L(a);this.tokens=[];this.pos=0;this.eof=false;this.bufferSize=k.system.lexingBufferLen;this._doBuffer()}c.prototype={_doBuffer:function(){try{for(var a=0;a<this.bufferSize;a++)this.tokens.push(this.lexer.getToken())}catch(c){this.eof=true}},setPos:function(a){this.pos=a},getPos:function(){return this.pos},isEnd:function(){return this.eof&&this.pos>=this.tokens.length-1},stepPos:function(a){this.pos+=typeof a!="undefined"?a:1},lookToken:function(a){return this.lookTokenByIndex(this.pos+
(a||0))},lookTokenByIndex:function(a){if(this.eof&&a>=this.tokens.length)throw"BufferEnd";a>=this.tokens.length&&this._doBuffer();var c=this.tokens[a];c.index=a;return c},findUntil:function(a,c,f){for(;;){if(a<0)break;else if(a>=this.tokens.length)break;else{var j=this.lookTokenByIndex(a);if(f(j))return j}a+=c}return null},getToken:function(){var a=this.lookToken();this.pos++;return a},getBufferRestSize:function(){return Math.max(this.tokens.length-this.pos-1,0)},skipUntil:function(a){for(;;){var c=
this.lookToken();if(!a(c))break;this.stepPos(1)}},skipUntilCRLF:function(){this.skipUntil(function(a){return!u.isTextToken(a)?false:a.data=="\r"||a.data=="\n"})},skipCRLF:function(){var a=this.lookToken();u.isTextToken(a)&&(a.data=="\r"?(this.stepPos(1),this.skipCRLF()):a.data=="\n"&&this.stepPos(1))}};return c}(),z=function(){function c(a){this.tags=[];this.tocs=[];this.topicPath=[];this.lastTopicPath=null;this.textSpaceAfter=this.textSpaceBefore=this.seekTextPos=this.seekCharCount=this.seekPageNo=
this.seekNextLine=this.seekNextChar=0;this.lineChars=[];this.rubyList=[];this.inlinePages=[];this.curToc=null;this.greedyMode=false;this.labelAttr=null;this.fontColor=k.color.defCharImgColor;this.updateFontSize(a.fontSize)}c.prototype={snap:function(){var a={},c=t.clone,f="tags,tocs,topicPath,lastTopicPath,seekNextChar,seekNextLine,seekCharCount,seekTextPos,textSpaceBefore,textSpaceAfter,lineChars,rubyList,inlinePages,curToc,greedyMode,labelAttr,fontSize,fontSize2,fontSize4,fontColor".split(",");
for(prop in f)a[prop]=c(this[prop]);return a},restoreSnap:function(a){for(prop in a)this[prop]=a[prop]},createBlock:function(a,c){return q.init({},{type:"block",name:"",width:0,height:0,content:""},c)},createImage:function(a,c){return q.init(this.createBlock(a,c),{src:""},c)},createInlineFrame:function(a,c){return q.init(this.createBlock(a,c),{src:"",frameborder:0},c)},createCaption:function(a,c){return q.init({},{type:"caption",data:"",captionPos:"",fontSize:a.captFontSize,height:a.captFontSize+
a.captMargin,"text-align":"center","margin-top":0,"margin-bottom":0},c)},createRuby:function(a,c){return q.init({},{type:"ruby",data:"",fontSize:this.fontSize2,textFontSize:this.fontSize,direction:a.direction,position:{x:0,y:0}},c)},createLine:function(a){if(this.labelAttr!=null){var c=this.createLabelLine(a,this.labelAttr);this.textSpaceBefore=Math.max(0,this.textSpaceBefore-a.labelSpace*2);this.textSpaceAfter=Math.max(0,this.textSpaceAfter-a.labelSpace*2);this.labelAttr=null}else c=this.createTextLine(a),
this.fixRubyPos(a);this.lineChars=[];this.rubyList=[];this.seekNextChar=0;return c},createTextLine:function(a){var c=this.getMaxFontSizeOfLine(a),f=a.enableRuby?Math.floor(c*a.leadingRate):c,j=this.getTextSpaceSize(),d=a.isVertical?f:a.maxNextChar-j,f=a.isVertical?a.maxNextChar-j:f,c={width:a.isVertical?c:a.width,height:a.isVertical?a.height:c};return{type:"line",width:d,height:f,direction:a.direction,fontSize:a.fontSize,textLineSize:c,rubyLineSize:{width:a.enableRuby?a.isVertical?d-c.width:a.width:
0,height:a.enableRuby?a.isVertical?a.height:f-c.height:0},childs:this.lineChars,rubyList:this.rubyList}},createLabelLine:function(a,c){var f=this.getMaxFontSizeOfLine(a),j=Math.floor(f*a.leadingRate),f=a.isVertical?j:this.seekNextChar+2*a.labelSpace,j=a.isVertical?this.seekNextChar+2*a.labelSpace:j;return{type:"label-line",width:f,height:j,direction:a.direction,fontSize:a.fontSize,textLineSize:{width:f,height:j},rubyLineSize:{width:0,height:0},childs:this.lineChars,textSpaceBefore:a.labelSpace,textSpaceAfter:a.labelSpace,
rubyList:[],attr:c}},createPage:function(a,c,f,j){return{type:"page",direction:a,width:c,height:f,childs:j}},createErrorMsg:function(a,c){var f=a.fontSize*5;return this.createInlineReader(a,{direction:"horizontal",width:a.isVertical?f:a.maxNextChar,height:a.isVertical?a.maxNextChar:f,theme:"error","class":"error",nopager:true,content:c})},createInlineReader:function(a,c){return q.init({},{type:"ireader","class":"",direction:a.direction,width:0,height:0,border:k.layout.readerBorder,fontSize:a.fontSize,
theme:"",syntax:"",nopager:false,content:""},c)},getTocs:function(){return this.tocs},pushTextToken:function(a){a.type=="char"||a.type=="rb"||a.type=="tcy"?this.pushCharToken(a):a.type=="word"&&this.pushWordToken(a)},pushTagToken:function(a){this.lineChars.push(a)},pushCharToken:function(a){this.seekNextChar+=a.stepSize;this.lineChars.push(a);u.isCharCountableToken(a)&&this.seekCharCount++;this.curToc!=null&&(this.curToc.title+=a.data)},pushWordToken:function(a){this.seekNextChar+=a.stepSize;this.lineChars.push(a);
this.seekCharCount+=a.data.length;this.curToc!=null&&(this.curToc.title+=a.data)},pushTopicPath:function(a){this.lastTopicPath!=null&&(a.level<this.lastTopicPath.level?(this.topicPath.pop(),this.topicPath.pop()):a.level==this.lastTopicPath.level&&this.topicPath.pop());this.topicPath.push(a);this.lastTopicPath=a},pushTocStartToken:function(a){var c=a.data.attr;this.curToc={level:c.level,title:"",pageNo:this.seekPageNo,id:c.id};this.tocs.push(this.curToc);this.pushTagToken(a)},pushTocEndToken:function(a){this.pushTopicPath(this.curToc);
this.curToc=null;this.pushTagToken(a)},pushRubyToken:function(a,c){this.rubyList.push(this.createRuby(a,{fontSize:Math.floor(this.fontSize*k.layout.rubySizeRate),textFontSize:this.fontSize,data:c.yomi,position:a.isVertical?{x:0,y:this.seekNextChar}:{x:this.seekNextChar,y:Math.floor((a.lineSpaceRate-k.layout.rubySizeRate)*this.fontSize/2)}}))},fixRubyPos:function(a){var c=this.getMaxFontSizeOfLine(a);c!=a.fontSize&&l.iter(this.rubyList,function(f){if(f.textFontSize<c)a.isVertical?f.position.x=-Math.floor((c-
f.textFontSize)/2):f.position.y=Math.floor((c-f.textFontSize)*(1+a.lineSpaceRate))})},startLabel:function(a,c){this.textSpaceBefore+=a.labelSpace*2;this.textSpaceAfter+=a.labelSpace*2;this.labelAttr=c.data.attr},endLabel:function(){},getTextSpaceSize:function(){return this.textSpaceBefore+this.textSpaceAfter},getRestCharSpace:function(a){return a.maxNextChar-this.seekNextChar-this.getTextSpaceSize()},getRestLineSpace:function(a){return a.maxNextLine-this.seekNextLine},getRestWidth:function(a){return a.isVertical?
this.getRestLineSpace(a):this.getRestCharSpace(a)},getRestHeight:function(a){return a.isVertical?this.getRestCharSpace(a):this.getRestLineSpace(a)},getMaxFontSizeOfLine:function(){return l.fold(this.lineChars,k.layout.minFontSize,function(a,c){return typeof c.fontSize!="undefined"&&c.fontSize>a?c.fontSize:a})},getCurFontSize:function(a){for(i=this.tags.length-1;i>=0;i--){var c=this.tags[i];if(c.name=="font"&&typeof c.attr.scale!="undefined")return Math.floor(a*c.attr.scale)}return a},getCurFontColor:function(){for(i=
this.tags.length-1;i>=0;i--){var a=this.tags[i];if(a.name=="font"&&typeof a.attr.color!="undefined")return a.attr.color}return k.color.defCharImgColor},updateFontSize:function(a){this.fontSize=a;this.fontSize2=Math.floor(a/2);this.fontSize4=Math.floor(a/4)},updateFontColor:function(a){this.fontColor=K.get(a)},pushTag:function(a){this.tags.push(a)},popTag:function(a){for(var c=[];this.tags.length>0;){var f=this.tags.pop();if(f.name==a)break;c.push(f)}for(;c.length>0;)this.tags.push(c.pop())}};return c}(),
G={code:{fontSizeRate:0.7,leadingRate:1.8},error:{fontSizeRate:1,leadingRate:1.8}},v=function(){function c(f){q.init(this,{direction:"vertical",theme:null,leadingRate:k.layout.defLeadingRate,width:400,height:300,fontSize:16,enableRuby:true,disableTailSpace:false,charImgColor:"000000"},f);this.update()}var a={vertical:{"page-size":"width","block-float":"right","line-text-align":"center","ruby-line-text-align":"left","margin-start":"margin-top","margin-end":"margin-bottom","margin-before":"margin-right",
"margin-after":"margin-left","border-before":"border-top","border-after":"border-bottom","border-prev":"border-right","border-next":"border-left",dummy:""},horizontal:{"page-size":"height","block-float":"left","line-text-align":"left","ruby-line-text-align":"left","margin-start":"margin-left","margin-end":"margin-right","margin-before":"margin-top","margin-after":"margin-bottom","border-before":"border-left","border-after":"border-right","border-prev":"border-top","border-next":"border-bottom",dummy:""}},
h={vertical:{"max-next-line":"width"},horizontal:{"max-next-line":"height"}};c.prototype={update:function(){if(this.theme!=null)this.fontSize=Math.floor(this.fontSize*(this.theme.fontSizeRate||1)),this.leadingRate=this.theme.leadingRate||this.leadingRate;this.isVertical=this.direction.match(/vertical/)?true:false;this.lineSpaceRate=this.leadingRate-1;this.blockMargin=Math.floor(this.fontSize*k.layout.blockMarginRate);this.labelSpace=Math.floor(this.fontSize*this.lineSpaceRate/2);this.captFontSize=
Math.floor(this.fontSize*k.layout.captionSizeRate);this.captMargin=Math.floor(this.captFontSize*k.layout.captionMarginRate);this.isVertical?(this.spaceForHeadNG=this.disableTailSpace?0:Math.floor(this.fontSize/2),this.maxNextChar=this.height-this.spaceForHeadNG,this.maxBlockWidth=this.maxNextLine=this.width,this.maxBlockHeight=this.maxNextChar-this.blockMargin):(this.spaceForHeadNG=this.disableTailSpace?0:this.fontSize,this.maxNextChar=this.width-this.spaceForHeadNG,this.maxNextLine=this.height,this.maxBlockWidth=
this.maxNextChar-this.blockMargin,this.maxBlockHeight=this.height)},getCssProp:function(f){return a[this.direction][f]},getProp:function(f){return h[this.direction][f]},getBlockRestWidth:function(f){return this.isVertical?f:this.maxBlockWidth-f},getBlockRestHeight:function(f){return this.isVertical?this.maxBlockHeight-f:f}};return c}(),H=function(){function c(f){this.forks=[];this.rest_size_list=f}function a(f,a,d){this.lexer=f;this.layout=a;this.ctx=typeof d!="undefined"?d:new z(a);this.forkset=
null;this.pushBlocks=[];this.finish=false;this.onParseElementBefore=function(b,d,f,a){return a}}var h=function(f,a){var d=f.isVertical?a.width||0:a.height||0;if(a.type=="page"&&a.tail)d=a.size;typeof a.border!="undefined"&&(d+=a.border*2);return d};c.prototype={add:function(f){this.forks.push(f)},hasNext:function(){return l.exists(this.forks,function(f){return f.hasNext()})},mergePages:function(f,a,d){if(d.length==1)return d[0];var b=l.fold(d,0,function(b,d){var e=h(f,d);return e>b?e:b}),e=f.getProp("max-next-line");
l.iter(d,function(d){d[e]=d.size=b});return a.createPage(f.direction,f.isVertical?b:f.width,f.isVertical?f.height:b,d)},yieldPage:function(f,a){var d=f.getProp("max-next-line"),b=this.rest_size_list.length>0?this.rest_size_list.shift():f[d],e=l.map(this.forks,function(e){var a=e.layout[d];e.args=e.args||{};e.layout[d]=b;e.args.border&&(e.layout[d]-=e.args.border*2);a!=e.layout[d]&&e.layout.update();e=e.parsePage(e.args);e.forked=true;return e});return this.mergePages(f,a,e)}};a.prototype={getContext:function(){return this.ctx},
hasNext:function(){return!this.finish},hasForkNext:function(){return l.exists(this.forks,function(a){return a.hasNext()})},findTextToken:function(a,j,d,b){for(var e=null,c={token:null,tags:[]},p=b;p<b+50;p++){var n=a.lookTokenByIndex(p);if(u.isBlockToken(n))break;if(u.isTextToken(n)){this.parseMetrics(a,j,e==null?d:e,n);c.token=n;break}if(n.type=="tag"){c.tags.push(n);var h=n.data.name;if(h=="font")e=e==null?t.clone(d):e,e.pushTag(n.data),e.fontSize=e.getCurFontSize(j.fontSize);else if(h=="/font")e=
e==null?t.clone(d):e,e.popTag("font"),e.fontSize=e.getCurFontSize(j.fontSize)}}return c},pushTextToLine:function(a,j,d,b){var e=d.getRestCharSpace(j),c=this.findTextToken(a,j,d,b.index+1);if(!(d.seekNextChar==0&&b.data==" "&&c.token.type=="word"))if(c.token==null||c.token.data=="\r"||c.token.data=="\n")d.pushTextToken(b);else if(e-b.stepSize>=c.token.stepSize)d.pushTextToken(b);else{if(k.system.lineBreakCheckLevel==0)throw"LineEnd";if(o.isTailNg(b.data))throw a.setPos(b.index),"LineEnd";if(!o.isHeadNg(c.token.data)||
c.token.type=="word")throw d.pushTextToken(b),a.skipCRLF(),"LineEnd";if(k.system.lineBreakCheckLevel==1)throw"LineEnd";e=this.findTextToken(a,j,d,c.token.index+1);if(e.token==null||!o.isHeadNg(e.token.data)){e.token.fontSize=j.fontSize;d.pushTextToken(b);d.pushTextToken(c.token);a.setPos(c.token.index+1);a.skipCRLF();for(b=0;b<c.tags.length;b++)this.parseLineTag(a,j,d,c.tags[b]);throw"LineEnd";}a.setPos(b.index);throw"LineEnd";}},pushLongWordToLine:function(a,j,d,b){var e=d.getRestCharSpace(j),c=
Math.floor(e/d.fontSize2),p=b.data.length,e=b.data.substring(0,c),c=b.data.substring(c,p),p=t.clone(b);p.data=e;this.parseMetrics(a,j,d,p);d.pushTextToken(p);a.setPos(b.index);b.data=c;this.parseMetrics(a,j,d,b);throw"LineEnd";},pushElementToPage:function(a,c,d,b,e){a=h(c,e);if(d.seekNextLine+a>c.maxNextLine)throw"Overflow";d.seekNextLine+=a;b.size+=a;b.childs.push(e);if(d.seekNextLine==c.maxNextLine)throw"EndPage";},parseMetrics:function(a,c,d,b){b.type=="char"||b.type=="rb"?b.src?this.parseMetricsIconChar(a,
c,d,b):b.img?this.parseMetricsImgChar(a,c,d,b):this.parseMetricsChar(a,c,d,b):b.type=="tcy"?this.parseMetricsTcy(a,c,d,b):b.type=="word"&&this.parseMetricsWord(a,c,d,b)},parseMetricsChar:function(a,c,d,b){a=c.isVertical?b.vscale:b.hscale;b.fontSize=d.fontSize;b.stepSize=a!=1?Math.floor(d.fontSize*a):d.fontSize;if(c.isVertical){if(b.cnv&&b.cnv=="&nbsp;")b.stepSize=d.fontSize2}else if(b.half)b.stepSize=d.fontSize2},parseMetricsImgChar:function(a,c,d,b){this.parseMetricsChar(a,c,d,b);if(c.isVertical)b.color=
d.fontColor;if(k.system.enableYakuMetricsCheck&&!(b.img.indexOf("kakko")<0&&b.img!="touten"&&b.img!="kuten")){var e=function(b){return u.isTextToken(b)||b.type=="ruby"},g=a.findUntil(b.index-1,-1,e),p="";if(g!=null)u.isTextToken(g)?p=g.data:g.type=="ruby"&&(p=g.kanji.substring(-1));e=a.findUntil(b.index+1,1,e);g="";if(e!=null)u.isTextToken(e)?g=e.data:e.type=="ruby"&&(g=e.kanji.substring(0,1));c.isVertical?this.parseMetricsMarginVert(a,c,d,b,p,g):this.parseMetricsMarginHori(a,c,d,b,p,g)}},parseMetricsMarginVert:function(a,
c,d,b,e,g){if(o.isKakkoStartChar(b.data)&&e!=""){if(!o.isKakkoStartChar(e)&&!o.isKutenTouten(e))b["margin-start"]=d.fontSize2,b.stepSize=d.fontSize}else if(o.isKakkoEndChar(b.data)&&g!=""){if(!o.isKakkoEndChar(g)&&!o.isKutenTouten(g))b["margin-end"]=d.fontSize2,b.stepSize=d.fontSize}else if(o.isKutenTouten(b.data)&&!o.isKakkoEndChar(g)&&!o.isKutenTouten(g))b["margin-end"]=d.fontSize2,b.stepSize=d.fontSize},parseMetricsMarginHori:function(a,c,d,b,e,g){if(r.isIE||b.fontSize<=k.layout.minKerningFontSize)b.hscale=
1;else if(o.isKakkoStartChar(b.data)&&g!=""){if(!o.isKakkoStartChar(g))b.hscale=1}else if(o.isKakkoEndChar(b.data)&&g!=""){if(!o.isKakkoEndChar(g)&&!o.isKutenTouten(g))b.hscale=1}else if(o.isKutenTouten(b.data)&&g!=""&&!o.isKakkoEndChar(g)&&!o.isKutenTouten(g))b.hscale=1},parseMetricsIconChar:function(a,c,d,b){a=c.isVertical?b.height:b.width;b.fontSize=a;b.stepSize=a},parseMetricsTcy:function(a,c,d,b){b.fontSize=d.fontSize;b.stepSize=d.fontSize},parseMetricsWord:function(a,c,d,b){b.fontSize=d.fontSize;
b.stepSize=b.data.length*d.fontSize2},parseChar:function(a,c,d,b){if(b.data!="\r"){if(b.data=="\n")throw"LineEnd";b.data==" "&&!d.greedyMode&&a.skipUntil(function(b){return b.type=="char"&&b.data==" "});this.parseMetrics(a,c,d,b);this.pushTextToLine(a,c,d,b)}},parseWord:function(a,c,d,b){typeof b.stepSize=="undefined"&&this.parseMetrics(a,c,d,b);b.stepSize>c.maxNextChar?this.pushLongWordToLine(a,c,d,b):this.pushTextToLine(a,c,d,b)},parseRuby:function(a,c,d,b){d.pushRubyToken(c,b)},parseFontStart:function(a,
c,d,b){a=b.data.attr;if(typeof a.scale!="undefined")c=a.scale=parseFloat(a.scale),d.updateFontSize(Math.floor(d.fontSize*c));typeof a.color!="undefined"&&d.updateFontColor(a.color);d.pushTag(b.data);d.pushTagToken(b)},parseFontEnd:function(a,c,d,b){d.pushTagToken(b);d.popTag("font");a=d.getCurFontSize(c.fontSize);c=d.getCurFontColor();d.updateFontSize(a);d.updateFontColor(c)},parseHeaderStart:function(a,c,d,b){var e=parseInt(b.data.name.substring(1))-1;b.data.name="font";b.data.attr.family="Meiryo";
b.data.attr.scale=k.layout.headerScales[e];this.parseFontStart(a,c,d,b)},parseHeaderEnd:function(a,c,d,b){b.data.name="/font";this.parseFontEnd(a,c,d,b);a.skipCRLF();throw"LineEnd";},parseTocStart:function(a,c,d,b){a=b.data.attr;a.level=parseInt(a.level||0);a.id=a.id||"";d.pushTocStartToken(b)},parseTocEnd:function(a,c,d,b){d.pushTocEndToken(b)},parseLabelStart:function(a,c,d,b){a.skipCRLF();d.updateFontColor(k.color.labelCharImgColor);d.startLabel(c,b)},parseLabelEnd:function(a,c,d,b){a=d.getCurFontColor();
d.updateFontColor(a);d.endLabel(c,b);throw"LineEnd";},parseIcon:function(a,c,d,b){var e=b.data.attr;b.width=parseInt(e.width||d.fontSize);b.height=parseInt(e.height||d.fontSize);b.src=e.src;b.type="char";delete b.data;b.data="";this.parseMetrics(a,c,d,b);this.pushTextToLine(a,c,d,b)},parseLineTag:function(a,c,d,b){switch(b.data.name){case "br":throw"LineEnd";case "pre":d.greedyMode=true;break;case "/pre":d.greedyMode=false;break;case "font":this.parseFontStart(a,c,d,b);break;case "/font":this.parseFontEnd(a,
c,d,b);break;case "h1":case "h2":case "h3":case "h4":case "h5":case "h6":this.parseHeaderStart(a,c,d,b);break;case "/h1":case "/h2":case "/h3":case "/h4":case "/h5":case "/h6":this.parseHeaderEnd(a,c,d,b);break;case "toc":this.parseTocStart(a,c,d,b);break;case "/toc":this.parseTocEnd(a,c,d,b);break;case "part":case "chapter":case "section":case "subsection":b.data.attr.level=Q.getLevel(b.data.name);b.data.name="toc";this.parseTocStart(a,c,d,b);break;case "/part":case "/chapter":case "/section":case "/subsection":b.data.name=
"/toc";this.parseTocEnd(a,c,d,b);break;case "label":this.parseLabelStart(a,c,d,b);break;case "/label":this.parseLabelEnd(a,c,d,b);break;case "icon":this.parseIcon(a,c,d,b);break;default:d.pushTagToken(b)}},parseLine:function(a,c,d){try{for(;;){var b=a.getToken();switch(b.type){case "char":case "rb":case "tcy":this.parseChar(a,c,d,b);break;case "word":this.parseWord(a,c,d,b);break;case "ruby":this.parseRuby(a,c,d,b);break;case "tag":this.parseLineTag(a,c,d,b)}}}catch(e){return e!="LineEnd"&&(r.isIE||
console.log(e)),d.createLine(c)}},parseBlockCaptions:function(a,c,d,b){var e=[];l.iter(["caption-head","caption-foot"],function(d){b[d]&&e.push(c.createCaption(a,{data:b[d],captionPos:d,"margin-bottom":d=="caption-head"?a.captMargin:0,"margin-top":d=="caption-foot"?a.captMargin:0}))});return e},parseBlockSizeAttr:function(a,c,d){a={width:0,height:0,border:0,"font-size":a.fontSize};for(prop in a)d[prop]=parseInt(typeof d[prop]=="undefined"?a[prop]:d[prop]);return d},parseBlockSize:function(a,c,d,b){var e=
d.border*2,g=c.getRestWidth(a),p=c.getRestHeight(a),b=l.fold(b,0,function(b,a){return b+a.height});if(d.width<=0||d.height<=0)return d.error="block size invalid("+d.width+","+d.height+")",d;var c=(a.isVertical?d.width:d.width+a.blockMargin)+e,h=(a.isVertical?d.height+a.blockMargin:d.height)+e+b;if(c<g&&h<p)return d;if(c<a.maxBlockWidth&&h<a.maxBlockHeight)throw"Overflow";c>g&&(h=g*h/c,c=Math.max(1,Math.floor(g)),h=Math.max(1,Math.floor(h)));h>p&&(c=Math.floor(c*p/h),h=Math.floor(p));g=k.layout.acceptableResizeRate*
d.width;p=k.layout.acceptableResizeRate*d.height;d.width=Math.max(0,(a.isVertical?c:c-a.blockMargin)-e);d.height=Math.max(0,(a.isVertical?h-a.blockMargin:h)-e-b);if(d.width<g||d.height<p)d.error="try to resize block, but not acceptable for this layout("+d.width+","+d.height+")";return d},parseImg:function(a,c,d,b){var b=this.parseBlockSizeAttr(c,d,b.data.attr),e=d.createImage(c,{name:"img",width:b.width,height:b.height,border:b.border,src:b.src});return this.parseBlockElement(a,c,d,e,b)},parseTable:function(a,
c,d,b){var e=this.parseBlockSizeAttr(c,d,b.data.attr),b=d.createBlock(c,{width:e.width,height:e.height,content:b.data.content,name:b.data.name});return this.parseBlockElement(a,c,d,b,e)},parseTextarea:function(a,c,d,b){var e=this.parseBlockSizeAttr(c,d,b.data.attr),b=d.createBlock(c,{width:e.width,height:e.height,content:b.data.content,name:b.data.name}),b=this.parseBlockElement(a,c,d,b,e);return q.copy(b,{onclick:e.onclick||""})},parseInlineFrame:function(a,c,d,b){var e=this.parseBlockSizeAttr(c,
d,b.data.attr),b=d.createInlineFrame(c,{width:e.width,height:e.height,content:b.data.content,name:b.data.name,src:e.src||"",frameborder:parseInt(e.frameborder||0)});return this.parseBlockElement(a,c,d,b,e)},parseInlinePage:function(a,c,d,b){q.copy(b.data.attr,{nopager:true});return this.parseInlineReader(a,c,d,b)},parseInlineReader:function(a,c,d,b){var e=b.data.attr;e.border=typeof e.border!="undefined"?parseInt(e.border):k.layout.readerBorder;e=this.parseBlockSizeAttr(c,d,e);b=d.createInlineReader(c,
{"class":e["class"]||"",direction:e.direction||c.direction,width:e.width,height:e.height,border:e.border,fontSize:parseInt(e["font-size"]||c.fontSize),theme:e.theme||"",syntax:e.syntax||"",nopager:e.nopager,content:t.cutHeadCRLF(b.data.content)});return this.parseBlockElement(a,c,d,b,e)},parseBlockElement:function(a,c,d,b,e){q.init(b,{"class":e["class"]||"",border:e.border,align:"",direction:c.direction},e);var g=this.parseBlockCaptions(c,d,b,e),b=this.parseBlockSize(c,d,b,g);if(b.error)return d.createErrorMsg(c,
"&lt;"+b.name+"&gt; "+b.error);g.length>0&&(b=this.parseBlockWithCaption(a,c,d,b,g));if(e.pushed)return this.parseBlockWithPush(a,c,d,b);else b.align!=""&&(b=this.parseBlockWithAlign(a,c,d,b));return b},parseBlockWithCaption:function(a,c,d,b,e){var g=[b],a=b.width,h=b.height;l.iter(e,function(a){h+=a.height;a.captionPos=="caption-head"?g.unshift(a):g.push(a)});d=d.createPage(b.direction,a,h,g);q.copy(d,{"class":b["class"]||"",direction:b.direction,align:b.align});delete b.align;delete b["class"];
return d},parseBlockWithPush:function(a,c,d,b){var e=c.blockMargin,g=c.isVertical?b.width+e:b.height+e;if(d.seekNextLine+g<c.maxNextLine)d.seekNextLine+=g,b["margin-before"]=e,b.push_size=g,this.pushBlocks.push(b);return this.parseElement(a,c,d)},parseBlockWithAlign:function(c,j,d,b){var e=b.align=="top"||b.align=="left",g=b.direction==j.direction,h=j.getBlockRestWidth(b.width),n=j.getBlockRestHeight(b.height),k=d.seekNextLine;d.seekNextLine=0;c=new a(c,new v({width:h,height:n,fontSize:j.fontSize,
direction:j.direction,disableTailSpace:g}),d);c.aligned=true;c.parent=this;c.offset=k;g={};g[e?"margin-start":"margin-end"]=j.blockMargin;g=c.parsePage(g);d.seekNextLine=k;g.aligned=true;this.forkset=c.forkset;return d.createPage(j.direction,j.isVertical?b.width:j.width,j.isVertical?j.height:b.height,e?[b,g]:[g,b])},parseBlockTag:function(a,c,d,b){a.stepPos();a.skipCRLF();switch(b.data.name){case "img":return this.parseImg(a,c,d,b);case "table":return this.parseTable(a,c,d,b);case "textarea":return this.parseTextarea(a,
c,d,b);case "iframe":return this.parseInlineFrame(a,c,d,b);case "ipage":return this.parseInlinePage(a,c,d,b);case "ireader":return this.parseInlineReader(a,c,d,b)}return null},parseIndent:function(a,c,d,b){var e=b.data.attr,g=k.layout.indent;e.before=parseInt(e.before||g.indentBefore);e.after=parseInt(e.after||g.indentAfter);if(e.count)e.count=e.before=e.after=parseInt(e.count);e.border=parseInt(e.border||0);e["margin-start"]=c.fontSize*e.before;e["margin-end"]=c.fontSize*e.after;return this.parseSingleForkPage(a,
c,d,b)},parseBlockquote:function(a,c,d,b){var e=b.data.attr,g=k.layout.blockquote;e["font-size"]=parseInt(e["font-size"]||Math.floor(c.fontSize*g.fontSizeRate));e.border=typeof e.border!="undefined"?parseInt(e.border):g.border;b.data.content=m.wrap("indent",{before:g.indentBefore,after:g.indentAfter,theme:e.theme||"",syntax:e.syntax||""},b.data.content);e.theme="";e.syntax="";return this.parseSingleForkPage(a,c,d,b)},parseFieldset:function(a,c,d,b){var e=b.data.attr,g=k.layout.fieldset,h=t.cutTagHeadSpace(b.data.content).replace(/<\/legend>[\s]+/,
"</legend>").replace(/<legend([^>]*)>(.+)<\/legend>/,"\n<label$1>$2</label>\n");e.border=g.border||1;e["font-size"]=parseInt(e["font-size"]||Math.floor(c.fontSize*g.fontSizeRate));b.data.content=m.wrap("indent",{before:g.indentBefore,after:g.indentAfter,raw:true,theme:e.theme||"",syntax:e.syntax||""},h);e.theme="";e.syntax="";return this.parseSingleForkPage(a,c,d,b)},parseDL:function(a,c,d,b){var e=b.data.attr,g=k.layout.dl;b.data.content=t.cutTagHeadSpace(b.data.content);if(g.indentBefore>0||g.indentAfter>
0)e.border=0,b.data.content=m.wrap("indent",{before:g.indentBefore,after:g.indentAfter},b.data.content);return this.parseSingleForkPage(a,c,d,b)},parseDT:function(a,c,d,b){var e=k.layout.dl.dt,g=b.data.attr;g["font-size"]=parseInt(g["font-size"]||Math.floor(c.fontSize*e.fontSizeRate));b.data.content=t.cutTagHeadSpace(b.data.content);b.data.content=m.wrap("strong",{},b.data.content);return this.parseSingleForkPage(a,c,d,b)},parseDD:function(a,c,d,b){var e=k.layout.dl.dd,g=b.data.attr;g["font-size"]=
parseInt(g["font-size"]||Math.floor(c.fontSize*e.fontSizeRate));b.data.content=t.cutTagHeadSpace(b.data.content);b.data.content=m.wrap("indent",{before:e.indentBefore,after:e.indentAfter},b.data.content);return this.parseSingleForkPage(a,c,d,b)},parseSingleForkPage:function(f,j,d,b){var e=b.data.content,b=b.data.attr;q.init(b,{"margin-start":0,"margin-end":0,border:0,"font-size":j.fontSize},b);b.border=parseInt(b.border);b["margin-start"]=parseInt(b["margin-start"]);b["margin-end"]=parseInt(b["margin-end"]);
var f=d.getRestLineSpace(j),g=b["margin-start"]+b["margin-end"],h=j.isVertical?f:j.maxNextChar-g,g=j.isVertical?j.maxNextChar-g:f,n=b.theme?G[b.theme]:null,e=new C(e),h=new v({direction:j.direction,width:h,height:g,theme:n,fontSize:parseInt(b["font-size"])}),e=new a(e,h);e.args=b;e.forked=true;e.parent=this;j.getProp("max-next-line");b=[f];this.aligned&&b.push(this.parent.layout.maxNextLine-(j.maxNextLine+this.offset));this.forkset=new c(b);this.forkset.add(e);return this.forkset.yieldPage(j,d)},
parseTextset:function(a,c,d,b){var e=b,g=k.layout.textset;for(e.childs=[];;)if(b=a.getToken(),b.type=="tag"){var h=b.data.name,n=b.data.attr;if(h=="/textset")break;if(h=="tpart")n.scale=parseFloat(n.scale||g.tpart.fontSizeRate),e.childs.push(b.data)}return this.parseSetForkPage(a,c,d,e)},parseUL:function(a,c,d,b){var e=b.data.attr,g=k.layout.ul,h=b.data.content.replace(/[\s]+(<\/?li)/gi,"$1");e.border=0;b.data.content=m.wrap("indent",{before:g.indentBefore,after:g.indentAfter},h);this.liCount=1;return this.parseSingleForkPage(a,
c,d,b)},parseLI:function(a,c,d,b){var e={childs:[]},g=this.parent.parent.forktag,h=k.layout[g]||k.layout.ul,n=h.li,b=b.data,n=parseFloat(b.attr.scale||n.fontSizeRate),w=Math.floor(c.fontSize*n);this.liIndex=this.parent.parent.liCount++;g=="ol"?c.isVertical?(h=w+w,g="<pack>"+this.liIndex+"</pack>&nbsp;"):(h=Math.floor(w*2.5),g=this.liIndex+".&nbsp;"):(g=h.listMark,h=w);g={content:g,attr:{scale:n,size:h}};b.attr.scale=n;b.content=t.cutEdgeCRLF(b.content);e.childs.push(g);e.childs.push(b);return this.parseSetForkPage(a,
c,d,e)},parseScenario:function(a,c,d,b){var e=b,g={},h=k.layout.scenario;for(e.childs=[];;)if(b=a.getToken(),b.type=="tag"){var b=b.data,n=b.name,w=b.attr;if(n=="/scenario")break;switch(n){case "sbody":var F=Math.floor(c.fontSize*h.sbody.marginRate);w.scale=parseFloat(w.scale||h[n].fontSizeRate);b.args={};b.args["margin-start"]=F;b.args["margin-end"]=F;g[n]=b;break;case "shead":case "sfoot":w.scale=parseFloat(w.scale||h[n].fontSizeRate),w.size=parseInt(w.size||h[n].size),g[n]=b}}h=["shead","sbody",
"sfoot"];for(b=0;b<h.length;b++)n=h[b],g[n]&&e.childs.push(g[n]);return this.parseSetForkPage(a,c,d,e)},parseSetForkPage:function(f,j,d,b){var e=this,f=b.childs,b=l.filter(f,function(a){return typeof a.attr.size!="undefined"}),g=l.fold(b,0,function(a,b){return a+parseInt(b.attr.size)}),h=Math.floor(((j.isVertical?j.height:j.width)-g)/(f.length-b.length)),n=d.getRestLineSpace(j),k=function(b,c,d,f){b=new a(new C(b),new v({direction:j.direction,width:j.isVertical?n:c,height:j.isVertical?c:n,fontSize:d}));
b.args=f;b.parent=e;return b},b=[n];this.aligned&&b.push(this.parent.layout.maxNextLine-(j.maxNextLine+this.offset));this.forkset=new c(b);b=0;for(g=f.length;b<g;b++)(function(a){var b=parseInt(a.attr.size||h);a.args=a.args||{};b-=a.args["margin-start"]||0;b-=a.args["margin-end"]||0;var c=Math.floor(parseFloat(a.attr.scale||1)*j.fontSize);e.forkset.add(k(a.content,b,c,a.args))})(f[b]);return this.forkset.yieldPage(j,d)},parseForkPageTag:function(a,c,d,b){a.stepPos();a.skipCRLF();switch(b.data.name){case "indent":return this.parseIndent(a,
c,d,b);case "blockquote":return this.parseBlockquote(a,c,d,b);case "ul":return this.parseUL(a,c,d,b);case "ol":return this.parseUL(a,c,d,b);case "li":return this.parseLI(a,c,d,b);case "dl":return this.parseDL(a,c,d,b);case "dt":return this.parseDT(a,c,d,b);case "dd":return this.parseDD(a,c,d,b);case "fieldset":return this.parseFieldset(a,c,d,b);case "textset":return this.parseTextset(a,c,d,b);case "scenario":return this.parseScenario(a,c,d,b)}return null},parseEndPage:function(a){this.aligned||(a.stepPos(),
a.skipUntilCRLF());throw"EndPage";},parseElement:function(a,c,d){if(this.forkset!=null&&this.forkset.hasNext())return this.forkset.yieldPage(c,d);try{var b=a.lookToken();d.seekTextPos=b.pos;b=this.onParseElementBefore(a,c,d,b)}catch(e){return r.isIE||console.log(e),null}if(u.isEndPageToken(b))return this.parseEndPage(a,c,d,b);if(u.isBlockToken(b))return this.parseBlockTag(a,c,d,b);return u.isForkPageToken(b)?(this.forktag=b.data.name,this.parseForkPageTag(a,c,d,b)):this.parseLine(a,c,d)},parsePage:function(a){var c=
this.ctx.createPage(this.layout.direction,this.layout.width,this.layout.height,[]);q.copy(c,{size:0,no:this.ctx.seekPageNo,head:this.ctx.seekPageNo==0,spos:this.ctx.seekTextPos,cpos:this.ctx.seekCharCount});q.copy(c,a||{});try{for(;;){var d=this.lexer.getPos(),b=this.ctx.snap(),e=this.parseElement(this.lexer,this.layout,this.ctx);if(e==null)throw this.finish=c.tail=true,"EndPage";else this.pushElementToPage(this.lexer,this.layout,this.ctx,c,e)}}catch(g){g=="Overflow"?(this.lexer.setPos(d),this.ctx.restoreSnap(b),
this.ctx.seekNextLine=0):g=="EndPage"?this.ctx.seekNextLine=0:r.isIE||console.log(g);if(this.pushBlocks.length>0)c.childs=c.childs.concat(this.pushBlocks),c.size+=l.fold(this.pushBlocks,0,function(a,b){return a+b.push_size}),this.pushBlocks=[];if(typeof this.aligned=="undefined")c.topicPath=t.clone(this.ctx.topicPath),this.ctx.seekPageNo++;return c}}};return a}(),I=function(){function c(){this.tags=[];this.ireaders=[]}c.prototype={getInlineReader:function(a){return this.ireaders[a]},pushInlineReader:function(a){var c=
this.ireaders.length;this.ireaders.push(a);return c},clearInlineReaders:function(){this.ireaders=[]},pushTag:function(a){this.tags.push(a)},popTag:function(a){z.prototype.popTag.call(this,a)},findTag:function(a){return l.find(this.tags,function(c){return c.name==a})}};return c}(),N=function(){function c(a,b){this.layout=a;this.ctx=typeof b!="undefined"?b:new I;this.handlers={}}var a=function(a,b){var c={};if(typeof b.scale!="undefined"){var d=Math.floor(b.scale*a.fontSize);c["font-size"]=d+"px";c["line-height"]=
d+"px"}if(typeof b.family!="undefined")c["font-family"]=b.family;if(typeof b.weight!="undefined")c["font-weight"]=b.weight;if(typeof b.color!="undefined")c.color=b.color;return c},h=function(a,b){var c=b.stepSize;return{clear:"both",height:c+"px","line-height":c+"px"}},f=function(a,b){var c=Math.floor(b.fontSize*b.vscale),c={width:b.fontSize+"px",height:c+"px","line-height":c+"px"};typeof b["margin-start"]!="undefined"&&(c[a.getCssProp("margin-start")]=b["margin-start"]+"px");typeof b["margin-end"]!=
"undefined"&&(c[a.getCssProp("margin-end")]=b["margin-end"]+"px");return c},j=function(a,b){var c=b.data,d=Math.floor(b.fontSize/2),e=typeof b["margin-start"]!="undefined"?b["margin-start"]:0,g=typeof b["margin-end"]!="undefined"?b["margin-end"]:0;c.length>2&&(g+=d*(c.length-2));c={"-webkit-transform":"rotate(90deg)","-webkit-transform-origin":"50% 50%","-moz-transform":"rotate(90deg)","-moz-transform-origin":"50% 50%","-o-transform":"rotate(90deg)","-o-transform-origin":"50% 50%",transform:"rotate(90deg)",
"transform-origin":"50% 50%"};c["margin-top"]=e+"px";c["margin-bottom"]=g+"px";return c},d=function(a,b){var c={"float":a.getCssProp("block-float"),width:b.width+"px",height:b.height+"px",margin:0,padding:0};b["margin-before"]&&(c[a.getCssProp("margin-before")]=b["margin-before"]+"px");return c},b=function(a,b){var c={"float":a.getCssProp("block-float"),width:b.width+"px",height:b.height+"px","border-width":b.border+"px",margin:0,padding:0};b["margin-before"]&&(c[a.getCssProp("margin-before")]=b["margin-before"]+
"px");return c},e=function(a,b,c){a={width:"100%","font-size":c.fontSize+"px","line-height":c.fontSize+"px","float":"left","text-align":"center",padding:0};typeof c["margin-bottom"]!="undefined"&&(a["margin-bottom"]=c["margin-bottom"]+"px");typeof c["margin-top"]!="undefined"&&(a["margin-top"]=c["margin-top"]+"px");typeof c["text-align"]!="undefined"&&(a["text-align"]=c["text-align"]);return a},g=function(a,b,c){a={position:"absolute","font-size":c.fontSize+"px","line-height":c.fontSize+"px"};a["margin-left"]=
c.position.x+"px";a["margin-top"]=c.position.y+"px";a["text-align"]="left";return a},p=function(a,b){var c=a.isVertical?b.fontSize:b.textLineSize.height,c={display:"block","float":a.getCssProp("block-float"),"text-align":a.getCssProp("line-text-align"),"font-size":b.fontSize+"px",width:b.textLineSize.width+"px",height:b.textLineSize.height+"px","line-height":c+"px"};r.isIE&&a.isVertical&&(c.overflow="hidden");return c},n=function(a,b){var c=a.isVertical?b.fontSize:b.rubyLineSize.height;return{display:"block",
"float":a.getCssProp("block-float"),width:b.rubyLineSize.width+"px",height:b.rubyLineSize.height+"px","line-height":c+"px"}},w=function(a,b){var c={display:"block",overflow:"visible","float":a.getCssProp("block-float"),width:b.width+"px",height:b.height+"px"};r.isMobileSafari&&(c["letter-spacing"]="-0.001em");return c},F=function(a,b){var c=w(a,b);b.attr["background-color"]&&(c["background-color"]=b.attr["background-color"]);c[a.isVertical?"height":"width"]="100%";return c},S=function(a,b){var c=
{"font-size":b.fontSize+"px","text-align":a.isVertical?"center":"left","line-height":b.fontSize+"px"};a.isVertical||(c.height=b.fontSize+"px");c[a.getCssProp("margin-start")]=b.textSpaceBefore+"px";c[a.getCssProp("margin-end")]=b.textSpaceAfter+"px";a.isVertical||(c["margin-top"]=Math.floor((b.height-b.fontSize)/2)+"px");b.attr.color&&(c.color=b.attr.color);return c},y=function(a,b){var c={};b.head||(c[a.getCssProp("border-prev")]="none");b.tail||(c[a.getCssProp("border-next")]="none");return c},
R=function(a,b){var c={display:"block","float":b["float"]||a.getCssProp("block-float"),width:b.width+"px",height:b.height+"px"};b.size&&(c[a.getCssProp("page-size")]=b.size+"px");b["margin-start"]&&(c[a.getCssProp("margin-start")]=b["margin-start"]+"px");b["margin-end"]&&(c[a.getCssProp("margin-end")]=b["margin-end"]+"px");b["margin-before"]&&(c[a.getCssProp("margin-before")]=b["margin-before"]+"px");b.border&&(c["border-width"]=b.border+"px",b.forked&&q.copy(c,y(a,b)));return c};c.prototype={getContext:function(){return this.ctx},
setOutputHandler:function(a,b){this.handlers[a]=b},callOutputHandler:function(a,b,c,d,e,g){return typeof this.handlers[a]!="undefined"?this.handlers[a](b,c,d,e,g):g},evalChar:function(a,b,c,d){return d.src?this.evalCharIcon(a,b,c,d):a.isVertical?this.evalCharVertical(a,b,c,d):this.evalCharHorizontal(a,b,c,d)},evalWord:function(a,b,c,d){return a.isVertical?this.evalWordVertical(a,b,c,d):d.data},evalTcy:function(a,b,c,d){return a.isVertical?d.data+"<br />":d.data},evalCharVertical:function(a,b,c,d){if(d.img)return this.evalCharImgVertical(a,
b,c,d);a=typeof d.cnv!="undefined"?d.cnv:d.data;return d.skana?m.wrap("div",{style:s.css({"font-size":d.fontSize+"px",overflow:"visible",position:"relative",top:"-0.2em",right:"-0.12em",height:d.stepSize+"px","line-height":d.stepSize+"px"})},a):a=="&nbsp;"?m.wrap("div",{style:s.css({"line-height":"0.5em",height:"0.5em"})},a):a+"<br />"},evalCharHorizontal:function(a,b,c,d){a=d.data==" "?"&nbsp;":d.data;return d.img&&d.hscale<1?m.wrap("span",{style:s.css({"letter-spacing":d.stepSize-d.fontSize+"px"})},
a):a},evalCharIcon:function(a,b,c,d){b=m.start("img",{"class":k.className.charIcon,width:d.width+"px",height:d.height+"px",style:s.css({}),src:d.src});return a.isVertical?b+"<br />":b},evalCharImgVertical:function(a,b,c,d){return m.wrap("div",{"class":k.className.charImg,style:s.css(h(a,d))},m.start("img",{src:o.ofImgSrc(d.img,d.color),style:s.css(f(a,d))}))},evalWordVertical:function(a,b,c,d){return m.wrap("div",{style:s.css(r.isIE?{"writing-mode":"tb-rl","line-height":d.fontSize+"px"}:j(a,d))},
d.data)},evalRubyBodyVert:function(a,b,c,d){a=d.data.length*d.fontSize;b=new C(d.data);a=new v({width:d.fontSize,height:a,fontSize:d.fontSize,enableRuby:false,disableTailSpace:true});c=new z(a);b=(new H(b,a)).parseLine(b,a,c);c=new I;return this.evalTextLineBody(a,c,d,b)},evalRubyBody:function(a,b,c,d){return/vertical/.test(d.direction)?this.evalRubyBodyVert(a,b,c,d):d.data},evalRuby:function(a,b,c,d){return m.wrap("div",{"class":k.className.rubyText,style:s.css(g(a,c,d))},this.evalRubyBody(a,b,c,
d))},evalCaption:function(a,b,c,d){return m.wrap("div",{"class":[k.className.caption,d.captionPos].join(" "),style:s.css(e(a,c,d))},t.escape(d.data))},evalStartLineTags:function(a,b,c){var d=this;return l.fold(b.tags,"",function(e,g){return g.name=="font"?e+d.evalFontStartBody(a,b,c,g):e+m.start(g.name,g.attr)})},evalCloseLineTags:function(a,b,c){var d=this;return l.fold(b.tags,"",function(e,g){return g.name=="font"?e+d.evalFontEndBody(a,b,c,g):e+m.end(g.name)})},evalRubyLine:function(a,b,c,d){if(d.rubyLineSize.width==
0||d.rubyLineSize.height==0)return"";var e=this,c=[k.className.rubyLine,a.direction].join("-");return m.wrap("div",{"class":[k.className.rubyLine,c].join(" "),style:s.css(n(a,d))},l.fold(d.rubyList,"",function(c,g){return c+e.evalRuby(a,b,d,g)}))},evalTextLineBody:function(a,b,c,d){var e=this;return this.callOutputHandler("onCompleteTextLineBody",a,b,c,d,[this.evalStartLineTags(a,b,c,d),l.fold(d.childs,"",function(c,g){return c+e.evalElement(a,b,d,g)}),this.evalCloseLineTags(a,b,c,d)].join(""))},
evalTextLine:function(a,b,c,d){var e=[k.className.textLine,a.direction].join("-");return m.wrap("div",{"class":[k.className.textLine,e].join(" "),style:s.css(p(a,d))},this.evalTextLineBody(a,b,c,d))},evalLineSet:function(a,b,c,d){return a.enableRuby?[this.evalRubyLine(a,b,c,d),this.evalTextLine(a,b,c,d)].join(""):this.evalTextLine(a,b,c,d)},evalLine:function(a,b,c,d){return m.wrap("div",{"class":k.className.line,style:s.css(w(a,d))},this.evalLineSet(a,b,c,d))},evalLabelLine:function(a,b,c,d){return m.wrap("div",
{"class":k.className.labelLine,style:s.css(F(a,d))},m.wrap("div",{"class":k.className.labelLineBody,style:s.css(S(a,d))},this.evalTextLineBody(a,b,c,d)))},evalImgBody:function(a,b,c,d){a=b.findTag("a");d=m.start("img",{src:d.src,width:d.width,height:d.height,style:s.css({"border-width":d.border+"px"})});return a!=null?m.wrap("a",a.attr,d):d},evalImg:function(a,b,c,e){return m.wrap("div",{"class":k.className.img,style:s.css(d(a,e))},this.evalImgBody(a,b,c,e))},evalBlock:function(a,c,d,e){if(e.name==
"img")return this.evalImg(a,c,d,e);a={"class":k.className.blockElement,style:s.css(b(a,e))};if(e.name=="iframe")a.src=e.src,a.frameborder=e.frameborder,a.width=e.width,a.height=e.height;else if(e.name=="textarea")a.onclick=e.onclick;return m.wrap(e.name,a,e.content)},evalInlineReader:function(a,c,d,e){c=c.pushInlineReader(e);return m.wrap("div",{"class":[k.className.inlineReader,"ireader-"+c].join(" "),style:s.css(b(a,e))},"")},evalLinkStart:function(a,b,c,d){a=d.attr;a.href=a.href||"";if(a.href.substring(0,
1)=="#")a["class"]=k.className.tocLink;b.pushTag(d);return m.start(d.name,d.attr)},evalLinkEnd:function(a,b,c,d){a=d.name.substring(1);b.popTag(a);return m.end(a)},evalBoldStart:function(a,b,c,d){b.pushTag(d);return m.start(d.name,d.attr)},evalBoldEnd:function(a,b,c,d){a=d.name.substring(1);b.popTag(a);return m.end(a)},evalFontStart:function(a,b,c,d){b.pushTag(d);return this.evalFontStartBody(a,b,c,d)},evalFontStartBody:function(b,c,d,e){return m.start(b.isVertical?"div":"span",{style:s.css(a(b,e.attr))})},
evalFontEnd:function(a,b,c,d){b.popTag("font");return this.evalFontEndBody(a,b,c,d)},evalFontEndBody:function(a){return a.isVertical?m.end("div"):m.end("span")},evalTag:function(a,b,c,d){d=d.data;switch(d.name){case "a":return this.evalLinkStart(a,b,c,d);case "/a":return this.evalLinkEnd(a,b,c,d);case "b":case "strong":return this.evalBoldStart(a,b,c,d);case "/b":case "/strong":return this.evalBoldEnd(a,b,c,d);case "font":return this.evalFontStart(a,b,c,d);case "/font":return this.evalFontEnd(a,b,
c,d)}return""},evalElement:function(a,b,d,e){switch(e.type){case "char":return this.evalChar(a,b,d,e);case "rb":return this.evalChar(a,b,d,e);case "word":return this.evalWord(a,b,d,e);case "tcy":return this.evalTcy(a,b,d,e);case "line":return this.evalLine(a,b,d,e);case "label-line":return this.evalLabelLine(a,b,d,e);case "caption":return this.evalCaption(a,b,d,e);case "ruby":return this.evalRuby(a,b,d,e);case "block":return this.evalBlock(a,b,d,e);case "ireader":return this.evalInlineReader(a,b,
d,e);case "tag":return this.evalTag(a,b,d,e);case "page":return(new c(new v({width:e.width,height:e.height,fontSize:a.fontSize,direction:e.direction||a.direction}),b)).evalPage(e)}return""},evalPage:function(a,b){var c=this,d=[];q.copy(a,b||{});a.forked?d.push(k.className.forkedPage):a.aligned?d.push(k.className.alignedPage):d.push(k.className.page);typeof a["class"]!="undefined"&&d.push(a["class"]);a.syntax&&this.setOutputHandler("onCompleteTextLineBody",M[a.syntax].editLine);return m.wrap("div",
{"class":d.join(" "),style:s.css(R(this.layout,a))},l.fold(a.childs,"",function(b,d){return b+c.evalElement(c.layout,c.ctx,a,d)}))}};return c}(),M={js:{editLine:function(c,a,h,f,j){return c.isVertical?j:j.replace(/[^:\"\'](\/\/.+)$/,"<span class='kw-cmt'>$1</span>").replace(/(\/\*[^\*]+\*\/)/,"<span class='kw-cmt'>$1</span>").replace(/(\"[^\"]+\")/g,"<span class='kw-string'>$1</span>")}},html:{editLine:function(c,a,h,f,j){return c.isVertical?void 0:M.js.editLine(c,a,h,f,j)}}},O=function(){function c(a,
c){this.lexer=new C(a);this.parser=new H(this.lexer,c);this.evaluator=new N(c)}c.prototype={hasNext:function(){return this.parser.hasNext()},getParser:function(){return this.parser},getEvaluator:function(){return this.evaluator},parsePage:function(a){return this.parser.parsePage(a)},evalPage:function(a,c){return this.evaluator.evalPage(a,c)},yieldPage:function(a){return this.evalPage(this.parsePage(a),a)}};return c}(),P=function(){function c(a,b){this.dom=document.createElement("div");this.dom.className=
d.className.screen;this.dom_s=this.dom.style;this.dom_s.width=a+"px";this.dom_s.height=b+"px";this.dom_s.margin=[d.screenSpaceTB+"px",d.screenSpaceLR+"px"].join(" ");this.dom_s.overflow="hidden";this.dom.innerHTML="<h2 class='"+d.className.loadingText+"'>LOADING...</h2>"}function a(a,b,c,f){var h=this;this.dom=document.createElement("div");this.dom.className=d.className.pager;this.dom_s=this.dom.style;this.dom_s.verticalAlign="middle";this.dom_s.fontSize=d.pager.fontSize+"px";this.dom_s.textAlign=
"center";this.dom_s.height=d.pager.height+"px";this.dom_s.lineHeight=d.pager.height+"px";this.dom_s.margin=d.pager.marginVert+"px 0";var j=document.createElement("a"),k=j.style;j.href="#btnNext";j.className=d.className.pagerNext.join(" ");j.onclick=function(){c();return false};k.width=d.pager.btnWidth+"px";var l=document.createElement("a"),m=l.style;l.href="#btnPrev";l.className=d.className.pagerPrev.join(" ");l.onclick=function(){b();return false};m.width=d.pager.btnWidth+"px";var B=document.createElement("span");
B.className=d.className.pagerStatus;B.style.width=d.pager.statusWidth+"px";this.curPage=document.createElement("input");this.curPage.className=d.className.pagerCurPage;this.curPage.type="text";this.curPage.value="0";this.curPage.style.width=d.pager.curPageInputWidth+"px";this.curPage.onkeypress=x.onkeypress(function(a){var b=h.getPageNo();a==13&&f(b)});this.pageSlash=document.createElement("span");this.pageSlash.innerHTML="/";this.pageSlash.style.margin="0 10px";this.totalPage=document.createElement("span");
this.totalPage.className=d.className.pagerTotalPage;B.appendChild(this.curPage);B.appendChild(this.pageSlash);B.appendChild(this.totalPage);a.indexOf("vertical")>=0?(j.innerHTML=d.pager.nextLinkTextVert,l.innerHTML=d.pager.prevLinkTextVert,k.marginRight="16px",m.marginLeft="16px",this.dom.appendChild(j),this.dom.appendChild(B),this.dom.appendChild(l)):(j.innerHTML=d.pager.nextLinkTextHori,l.innerHTML=d.pager.prevLinkTextHori,m.marginRight="16px",k.marginLeft="16px",this.dom.appendChild(l),this.dom.appendChild(B),
this.dom.appendChild(j))}function h(){this.dom=document.createElement("div");this.dom.className=d.className.footer;this.dom_s=this.dom.style;this.dom_s.textAlign="right";this.dom_s.marginRight=d.defFontSize+"px";this.dom_s.marginTop=d.footer.marginVert+"px";this.dom_s.height=d.footer.height+"px";this.dom_s.lineHeight=d.footer.height+"px";var a=document.createElement("div");a.className=d.className.copy;a.style.fontSize="0.9em";a.innerHTML="powered by <a target='_blank' href='https://code.google.com/p/nehan/'>nehan</a> layout engine.";
this.dom.appendChild(a)}function f(a,b){this.reader=a;this.offset=0;this.keyword=b}function j(a){this.nospace=typeof a.nospace!="undefined"?a.nospace:false;this.isinline=typeof a.isinline!="undefined"?a.isinline:false;this.nopager=typeof a.nopager!="undefined"?a.nopager:false;this.border=typeof a.border!="undefined"?a.border:k.layout.readerBorder;this.width=a.width||d.defOuterWidth;this.height=a.height||d.defOuterHeight;this.screenWidth=this.width-d.screenSpaceLR*2;this.screenHeight=this.height-d.screenSpaceTB*
2;this.nopager==false&&(this.screenHeight-=d.pager.height+d.pager.marginVert*2);this.isinline==false&&(this.screenHeight-=d.footer.height+d.footer.marginVert);this.pages=[];this.caches=[];this.ireaders=[];this.bookmarks=[];this.pageNo=this.progress=0;this.complete=false;this.direction=a.direction||d.defDirection;this.text=a.text||"no text";this.theme=G[a.theme]||null;this.syntax=a.syntax||"";this.className=a.className;this.pageLayout=new v({direction:this.direction,theme:this.theme,width:this.screenWidth,
height:this.screenHeight,fontSize:a.fontSize||d.defFontSize,leadingRate:a.leadingRate||d.defLeadingRate});this.generator=new O(this.text,this.pageLayout);this.onStart=a.onStart||function(){};this.onProgress=a.onProgress||function(){};this.onComplete=a.onComplete||function(){};this.onWritePageStart=a.onWritePageStart||function(){};this.onWritePageEnd=a.onWritePageEnd||function(){}}var d={defDirection:"horizontal",defFontSize:20,defOuterWidth:600,defOuterHeight:400,defLeadingRate:1.8,screenSpaceTB:20,
screenSpaceLR:32,borderWidth:1,maxSearchResult:10,maxSearchExcerptLen:20,className:{targetMarkup:"nehan-pagerize",screenWrap:"nehan-pagerize-screen-wrap",screen:"nehan-pagerize-screen",pager:"nehan-pagerize-pager",footer:"nehan-pagerize-footer",copy:"nehan-pagerize-copyright",pagerStatus:"nehan-pagerize-pager-status",pagerCurPage:"nehan-pagerize-pager-cur-page",pagerTotalPage:"nehan-pagerize-pager-total-page",pagerNext:["nehan-button","nehan-button-orange","nehan-pagerize-pager-next"],pagerPrev:["nehan-button",
"nehan-button-blue","nehan-pagerize-pager-prev"],loadingText:"nehan-pagerize-loading-text"},pager:{fontSize:16,height:30,marginVert:5,btnWidth:80,statusWidth:140,curPageInputWidth:30,nextLinkTextVert:"<span>&laquo; NEXT</span>",prevLinkTextVert:"<span>PREV &raquo;</span>",nextLinkTextHori:"<span>NEXT &raquo;</span>",prevLinkTextHori:"<span>&laquo; PREV</span>"},footer:{height:20,marginVert:5},system:{parsingLoop:20,parsingLoopIE:10,parsingSleepIE:10}},b={_findTargetNodes:function(){var a=document.getElementsByTagName("pre");
return l.filter(a,function(a){return a.className.indexOf(d.className.targetMarkup)>=0})},parseOpt:function(a){a=a||{};q.init(a,{width:d.defOuterWidth,height:d.defOuterHeight,fontSize:d.defFontSize,direction:d.defDirection},a);return a},map:function(a){var a=this.parseOpt(a),b=this._findTargetNodes();l.iter(b,function(b){var c=b.className,d=t.clone(a);d.text=b.innerHTML;if(c.indexOf("lp-horizontal")>=0)d.direction="horizontal";else if(c.indexOf("lp-vertical")>=0)d.direction="vertical";(new j(d)).start(b)})},
createReader:function(a){a=this.parseOpt(a);return new j(a)}};c.prototype={getDOM:function(){return this.dom},getInlineReaderDOMs:function(){return l.filter(this.dom.getElementsByTagName("div"),function(a){return a.className&&a.className.indexOf(k.className.inlineReader)>=0?true:false})},update:function(a){this.dom.innerHTML=a}};a.prototype={getDOM:function(){return this.dom},getPageNo:function(){return Math.max(0,parseInt(this.curPage.value)-1)},setPageNo:function(a){this.curPage.value=a},setPageCount:function(a){this.totalPage.innerHTML=
a}};h.prototype={getDOM:function(){return this.dom}};f.prototype={hasNext:function(){return this.offset>=0},getNext:function(){for(var a=this.reader,b=this.reader.getText(),c=this.keyword,f=[],h=0;h<d.maxSearchResult;h++){this.offset=b.indexOf(c,this.offset+1);if(this.offset<0)break;f.push(this.offset)}var j=function(a){return a.replace(RegExp("("+c+")","g"),function(a,b){return"<strong>"+t.escape(b)+"</strong>"})};return l.map(f,function(f){var h=a.findPageNo(f),k=a.getSourceText(h),k=d.maxSearchExcerptLen,
k=b.substring(f,f+c.length+k),k=k.replace(/<rt>[^<]+<\/rt>/g,""),k=k.replace(/<[^>]+>/g,""),k=t.escape(k),k=j(k);return{spos:f,pageNo:h,text:k}})}};j.prototype={start:function(a){this.setupUI(a);this.complete=false;this.progress=0;this.onStart(this);this.addPage(this.parsePage());this.writePage(0);if(this.pager)this.parsePageBg();else this.onComplete(this)},setupUI:function(b){var g=this;b.innerHTML="";this.dom=b;this.dom.className=[d.className.screenWrap,this.dom.className,this.className].join(" ");
this.dom_s=b.style;this.dom_s.overflow="hidden";this.dom_s.display="block";this.dom_s.width=this.width+"px";this.dom_s.height=this.height+"px";this.dom_s.borderWidth=this.border+"px";this.screen=new c(this.screenWidth,this.screenHeight);this.dom.appendChild(this.screen.getDOM());if(this.nopager==false)this.pager=new a(this.direction,function(){g.writePrev()},function(){g.writeNext()},function(a){g.writePage(a)}),this.dom.appendChild(this.pager.getDOM());if(this.isinline==false)this.footer=new h,this.dom.appendChild(this.footer.getDOM())},
resume:function(a){this.setupUI(a);this.setPageCount(this.pages.length);this.writePage(this.pageNo)},parsePage:function(){var a=this.generator.parsePage();a.syntax=this.syntax;return a},getGenerator:function(){return this.generator},getText:function(){return this.text},getDirection:function(){return this.direction},getTocs:function(){return this.generator.getParser().getContext().getTocs()},getPageNo:function(){return this.pageNo},getTotalPageCount:function(){return this.pages.length},getDOM:function(){return this.dom},
getPageJson:function(a){return this.pages[a]||null},getTopicPath:function(a){a=this.getPageJson(a);return a!=null?a.topicPath:null},getTopicPathTitle:function(a){return l.map(a,function(a){return a.title}).join("/")},makeBookmark:function(a){a=this.getPageJson(a);return a==null?null:this.getTopicPathTitle(a.topicPath)},setBookmark:function(a){var b=this.makeBookmark(a);return this.bookmarks[a]=b},deleteBookmark:function(a){this.bookmarks[a]=null},getBookmarks:function(){return this.bookmarks},getPageCache:function(a){return this.caches[a]||
null},setPageCache:function(a,b){this.caches[a]=b},setPageNo:function(a){this.pager&&this.pager.setPageNo(a)},setPageCount:function(a){this.pager&&this.pager.setPageCount(a)},getSourceText:function(a){var b=this.getPageJson(a),a=this.getPageJson(Math.max(a+1,this.pages.length-1));return b==null||a==null?"":this.text.substring(b.spos,a.spos)},findPageNo:function(a){for(var b=0,c=this.pages.length;b<c;b++){var d=this.pages[b].spos;if(d>a)return Math.max(0,b-1);else if(d==a)return b}return-1},searchKeyword:function(a){return new f(this,
a)},getSeekPos:function(a){return this.pages[a]?(a=this.pages[a],{cpos:a.cpos,spos:a.spos}):null},addPage:function(a){this.pages.push(a);return a},parsePageBg:function(){for(var a=null,b=r.isIE?d.system.parsingLoopIE:d.system.parsingLoop,c=0;c<b;c++){if(!this.generator.hasNext()){this.setPageCount(this.pages.length);this.complete=true;this.onComplete(this);return}a=this.addPage(this.parsePage())}if(a)this.progress=Math.floor(100*(a.spos||0)/this.text.length),this.setPageCount("("+this.progress+"%)"),
this.onProgress(this,this.progress,this.pages.length);var f=this;setTimeout(function(){f.parsePageBg()},r.isIE?d.system.parsingSleepIE:0)},getInlineReaderFromCache:function(a,b){return this.ireaders[a]&&this.ireaders[a][b]?this.ireaders[a][b]:null},cacheInlineReader:function(a,b,c){this.ireaders[a]||(this.ireaders[a]=[]);this.ireaders[a][b]=c},setupTocLinks:function(){var a=this,b=this.screen.getDOM().getElementsByTagName("a");l.iter(b,function(b){if(b.className==k.className.tocLink){var c=b.href.split("#");
if(c.length>0){var d=c[1];b.onclick=function(){a.writePageByTocId(d);return true}}}})},writeInlineReaders:function(a,b){var c=this,d=this.generator.getEvaluator().getContext();l.iter(b,function(b){if(b.className.match(/ireader-([\d]+)/)){var f=parseInt(RegExp.$1),g=c.getInlineReaderFromCache(a,f);g!=null?g.resume(b):(g=d.getInlineReader(f),g=new j({text:g.content,className:g["class"],direction:g.direction,fontSize:g.fontSize,width:g.width,height:g.height,theme:g.theme,syntax:g.syntax,border:g.border,
nopager:g.nopager,isinline:true}),g.child=true,g.start(b),c.cacheInlineReader(a,f,g))}})},writePageByTocId:function(a){var b=l.find(this.getTocs(),function(b){return b.id==a});b!=null&&this.writePage(b.pageNo)},writePageWithCache:function(a){var b=this.getPageJson(a);if(b!=null){var c=this.getPageCache(a);c==null&&(c=this.generator.evalPage(b),this.setPageCache(a,c));this.setPageNo(a+1);this.screen.update(c);this.writeInlineReaders(a,this.screen.getInlineReaderDOMs());this.setupTocLinks()}},writePage:function(a){(a>=
this.pages.length||a<0)&&alert("pageNo("+a+") is not available for this book");this.pageNo=a;this.onWritePageStart(this,a);this.writePageWithCache(a);this.onWritePageEnd(this,a)},writeNext:function(){this.pageNo<this.pages.length-1&&this.writePage(this.pageNo+1)},writePrev:function(){this.pageNo>0&&this.writePage(this.pageNo-1)}};b.pgconfig=d;return b}(),T=function(){var c=function(a,b,c){var f=document.createElement("a");f.href="#"+a;f.innerHTML=b;f.onclick=function(){c.writePage(a);return true};
return f},a=function(a,b,e){var f=document.createElement("table"),h=document.createElement("thead"),j=document.createElement("tr"),k=document.createElement("th"),l=document.createElement("th"),m=document.createElement("th"),y=document.createElement("tbody");f.className="nehan-book-bmark-table";f.style.borderCollapse="collapse";k.innerHTML="topic path";l.innerHTML="page";m.innerHTML="delete";j.appendChild(k);j.appendChild(l);j.appendChild(m);h.appendChild(j);f.appendChild(h);f.appendChild(y);a.appendChild(f);
var o=function(a,b){var d=document.createElement("tr"),f=document.createElement("td"),g=document.createElement("td"),h=document.createElement("td"),j=c(a,b,e),k=document.createElement("a");k.href="#delete";k.innerHTML="delete";k.onclick=function(){e.deleteBookmark(a);y.removeChild(d);return false};f.appendChild(j);g.innerHTML=a+1;h.appendChild(k);d.appendChild(f);d.appendChild(g);d.appendChild(h);return d};b.onclick=function(){var a=e.getPageNo(),b=e.setBookmark(a);bmark!=null&&(a=o(a,b),y.appendChild(a));
return false}},h=function(a,b,c,g){var h=function(a){a!=""&&(a=g.searchKeyword(a),f(c,g,a))};a.onkeypress=x.onkeypress(function(b){b==13&&h(a.value)});b.onclick=function(){h(a.value);return false}},f=function(a,b,c){a.innerHTML="";a.style.overflow="hidden";var g=c.getNext();if(g.length==0)a.innerHTML="<p>not found</p>";else{var h=function(){var g=document.createElement("p"),h=document.createElement("a");h.href="#more";h.innerHTML="more result";h.onclick=function(){f(a,b,c);return false};g.appendChild(h);
return g},j=function(a){var c=document.createElement("tr"),d=document.createElement("td"),e=document.createElement("a");e.innerHTML="p"+(a.pageNo+1);e.href="#"+a.pageNo;e.onclick=function(){b.writePage(a.pageNo);return false};d.appendChild(e);e=document.createElement("td");e.innerHTML=a.text;c.appendChild(d);c.appendChild(e);return c},k=function(){var a=document.createElement("table"),b=document.createElement("thead"),c=document.createElement("tr"),d=document.createElement("th");d.innerHTML="page";
var e=document.createElement("th");e.innerHTML="text";c.appendChild(d);c.appendChild(e);b.appendChild(c);a.appendChild(b);return a}(),m=document.createElement("tbody");k.appendChild(m);l.iter(g,function(a){m.appendChild(j(a))});g=function(){var b=document.createElement("p"),c=document.createElement("a");c.innerHTML="clear search result";c.href="#clear";c.onclick=function(){a.innerHTML="";return false};b.appendChild(c);return b}();a.appendChild(g);a.appendChild(k);c.hasNext()&&(h=h(),a.appendChild(h))}},
j=function(a,b,c){a.innerHTML="";c=b.getTopicPath(c);if(c!=null){var f=Math.max(0,c.length-1);l.iteri(c,function(c,e){var h=document.createElement("a");h.innerHTML=e.title;h.href="#"+e.pageNo;h.onclick=function(){b.writePage(e.pageNo);return false};a.appendChild(h);if(c!=f)h=document.createElement("span"),h.innerHTML="/",h.style.margin="0 0.5em",a.appendChild(h)})}};return{start:function(d){var b=new Date,e=0,f="",l=document.getElementById(d.ui.topicPathId||"topic-path"),m=document.getElementById(d.ui.tocId||
"toc"),o=document.getElementById(d.ui.searchInputId||"search-input"),s=document.getElementById(d.ui.searchBtnId||"search-btn"),t=document.getElementById(d.ui.searchResultId||"search-result"),q=document.getElementById(d.ui.bookBodyId||"book-body"),r=d.text||(q?q.innerHTML:"body text not found"),u=document.getElementById(d.ui.bmarkId||"bmark"),x=document.getElementById(d.ui.bmarkBtnId||"bmark-btn");q.innerHTML="";r=P.createReader({text:r,direction:d.direction||"horizontal",width:d.width||700,height:d.height||
600,fontSize:d.fontSize||18,onStart:function(a){if(location.href.match("#")){var b=location.href.split("#")[1];isNaN(b)?f=b:e=parseInt(b)}if(d.onStart)d.onStart(a)},onComplete:function(j){var l=(new Date-b)/1E3;if(m){var q=j.getTocs(),p=document.createElement("ul"),r=p,v=null;p.className="nehan-toc-root";for(var y=0,C=q.length;y<C;y++){var A=q[y],E=document.createElement("li"),z=c(A.pageNo,A.title||"no title",j);E.appendChild(z);if(v==null)r.appendChild(E);else if(A.level==v.level)r.appendChild(E);
else if(A.level>v.level){var v=A.level,z=document.createElement("ul"),D=k.tags.toc;z.className="nehan-toc-level-"+D[v%D.length];ul=z;ul.appendChild(E);r.appendChild(ul);r=ul}else A.level<v.level&&(r=A.level<=0?p:r.parentNode,r.appendChild(E));v=A}m.appendChild(p)}o&&s&&t&&h(o,s,t,j);u&&x&&a(u,x,j);if(d.onComplete)d.onComplete(j,l);e>0?j.writePage(e):f!=""&&j.writePageByTocId(f)},onProgress:function(){},onWritePageStart:function(){window.scroll(0,0)},onWritePageEnd:function(a,b){j(l,a,b)}});if(d.onBeforeStart)d.onBeforeStart(r);
r.start(q)}}}();Nehan3.version="3.0.2";Nehan3.env=r;Nehan3.config=k;Nehan3.Pagerize=P;Nehan3.Book=T;Nehan3.Util=t;Nehan3.Closure=x;Nehan3.Args=q;Nehan3.List=l;Nehan3.Attr=s;Nehan3.Tag=m;Nehan3.Token=u;Nehan3.Char=o;Nehan3.Word=J;Nehan3.CharImgColor=K;Nehan3.Lexer=L;Nehan3.BufferedLexer=C;Nehan3.Layout=v;Nehan3.Theme=G;Nehan3.ParserContext=z;Nehan3.DocumentParser=H;Nehan3.EvalContext=I;Nehan3.NehanEvaluator=N;Nehan3.PageGenerator=O})();



