Nehan.setStyles({
  "body":{
    "font-size":16,
    "padding":{
      "start":"10px",
      "end":"10px",
      "after":"10px"
    },
    "border-color":"wheat",
    "border-style":"solid",
    "border-width":"5px",
    "border-radius":"5px",
    "background-color":"wheat"
  },
  "blockquote":{
    "color":"#444",
    "background-color":"#dcdcdc",
    "border-style":{
      "start":"solid"
    },
    "border-color":{
      "start":"#888"
    },
    "padding":{
      "start":"5px"
    },
    "margin":{
      "start":"10px",
      "end":"10px"
    },
    "border-width":{
      "start":"5px"
    }
  }
});

